### plot_gatk_cna_summary.R ########################################################################
# Plot CNA landscape
# INPUT:
#	- copy number calls and pga estimates (output by collect_gatk_cnv_output.R)

### FUNCTIONS ######################################################################################
# function to generate a standardized filename
generate.filename <- function(project.stem, file.core, extension, include.date = TRUE) {

	# build up the filename
	file.name <- paste(project.stem, file.core, sep = '_');
	file.name <- paste(file.name, extension, sep = '.');

	if (include.date) {
		file.name <- paste(Sys.Date(), file.name, sep = '_');
		}

	return(file.name);
	}

# function to write session profile to file
save.session.profile <- function(file.name) {

	# open the file
	sink(file = file.name, split = FALSE);

	# write memory usage to file
	cat('### MEMORY USAGE ###############################################################');
	print(proc.time());

	# write sessionInfo to file
	cat("\n### SESSION INFO ###############################################################");
	print(sessionInfo());

	# close the file
	sink();

	}

# function to trim sample IDs
simplify.ids <- function(x) {
	match <- TRUE;
	index <- 1;
	while (match) {
		if (length(unique(sapply(x,function(i) { unlist(strsplit(i,''))[index] } ))) == 1) {
			index <- index + 1;
			} else {
			new.ids <- sapply(x,function(i) { substring(i,index,nchar(i)) } );
			match <- FALSE;
			}
		}
	return(new.ids);
	}

### PREPARE SESSION ################################################################################
# import libraries
library(xtable);
library(BoutrosLab.plotting.general);
library(argparse);

# import command line arguments
parser <- ArgumentParser();

parser$add_argument('-p', '--project', type = 'character', help = 'PROJECT name');
parser$add_argument('-o', '--output', type = 'character', help = 'path to output directory');
parser$add_argument('-c', '--cnas', type = 'character', help = 'path to gene by sample matrix of cna calls (generated by collect_sequenza_output.R)');
parser$add_argument('-m', '--metrics', type = 'character', help = 'path to ploidy and cellularity estimates (generated by collect_sequenza_output.R)');

arguments <- parser$parse_args();

### READ DATA ######################################################################################
# get data
input.data <- read.delim(arguments$cnas);
pga <- read.delim(arguments$metrics, row.names = 1);

# move to output directory
setwd(arguments$output);

### FORMAT DATA ####################################################################################
# make sure pga data is sorted
pga$Order <- 1:nrow(pga);
pga <- pga[order(pga$PGA),];
pga$Order <- 1:nrow(pga);

# collect list of all (ordered) samples
all.samples <- rownames(pga);

# makes sure input.data is sorted
input.data$Chromosome <- factor(input.data$Chromosome, levels = paste0('chr',c(1:22,'X','Y')));
input.data <- input.data[order(input.data$Chromosome, input.data$Start),];
input.data <- input.data[which(input.data$Chromosome != 'chrY'),];
rownames(input.data) <- input.data$GeneID;

# ensure sample names match
if (!any(all.samples %in% colnames(input.data))) {
	if ( (any(grepl('-', all.samples))) && (!any(grepl('-', colnames(input.data)))) ) {
		alt.sample.names <- gsub('-', '.', all.samples);
		}
	if ( (any(grepl("^[[:digit:]]", all.samples))) && (any(grepl('^X',colnames(input.data)))) ) {
		alt.sample.names <- paste0('X', alt.sample.names);
		}
	if (!any(alt.sample.names %in% colnames(input.data))) {
		stop('Correlation sample names do not match names from other tables');
		}
	cna.data <- input.data[,alt.sample.names];
	} else {
	cna.data <- input.data[,all.samples];
	}

### PLOT DATA ######################################################################################
# grab some parameters
axis.cex <- if (ncol(cna.data) <= 30) { 1
	} else if (ncol(cna.data) <= 50) { 0.75
	} else if (ncol(cna.data) <= 80) { 0.5
	} else if (ncol(cna.data) <= 100) { 0
	} else { 0 };

chromosomes <- gsub('chr','',tolower(input.data$Chromosome));
chr.breaks <- get.line.breaks(chromosomes);
covariate.colours <- force.colour.scheme(chromosomes, scheme = 'chromosome');

covariate.legends <- legend.grob(
	legends =  list(
		legend = list(
			colours = force.colour.scheme(c(1:22,'x'), scheme = 'chromosome'),
			labels = c(1:22,'X')
			),
		legend = list(
			colours = c('red','white','blue'),
			labels = c('+1','0','-1')
			)
		),
	size = 2
	);

# create heatmap
cna.plot <- create.heatmap(
	cna.data,
	cluster.dimensions = 'none',
	covariates.top = list(
		rect = list(
			col = 'black',
			fill = covariate.colours,
			lwd = 0
			)
		),
	covariates.top.grid.border = list(col = 'black', lwd = 1),
	covariates.top.grid.col = list(col = 'black', lwd = 1),
	covariates.top.col.lines = chr.breaks,
#	inside.legend = list(fun = covariate.legends, x = 1.08, y = 1),
	yaxis.lab = gsub('\\.','-', simplify.ids(colnames(cna.data))),
	xaxis.lab = rep('',nrow(cna.data)),
	yaxis.cex = axis.cex,
	xaxis.tck = 0,
	yaxis.tck = if (axis.cex == 0) { 0 } else { 0.2 },
	yaxis.fontface = 'plain',
	axes.lwd = 1,
	col.colour = 'black',
	grid.col = TRUE,
	force.grid.col = TRUE,
	col.lines = chr.breaks,
	print.colour.key = FALSE,
	fill.colour = 'grey50',
	at = seq(-1.5,1.5,1),
	colour.scheme = c('blue','white','red'),
	colourkey.labels.at = seq(-1,1,1),
	colourkey.labels = c('loss','neutral','gain'),
	colourkey.cex = 1
	);

# create plot for PGA
pga.plot <- create.barplot(
	Order ~ PGA,
	pga,
	yaxis.lab = rep('', nrow(pga)),
	ylimits = c(0.5, length(all.samples)+0.5),
	yat = seq(1,length(all.samples)),
	xaxis.tck = c(0.5,0),
	yaxis.tck = 0,
	xaxis.fontface = 'plain',
	yaxis.fontface = 'plain',
	xlab.label = "PGA\n",
	xlab.cex = 1,
	ylab.label = NULL,
	xlimits = c(0,100),
	xat = seq(0,100,50),
	xaxis.cex = 1,
	axes.lwd = 1,
	top.padding = 0,
	plot.horizontal = TRUE
	);

# combine them!
create.multipanelplot(
	plot.objects = list(cna.plot, pga.plot),
	height = if (nrow(pga) <= 30) { 6 } else { 8 },
	width = 12,
	resolution = 200,
	filename = generate.filename(arguments$project, 'gatk_scna_landscape','png'),
	layout.width = 2,
	layout.height = 1,
	legend = list(right = list(fun = covariate.legends)),
	plot.objects.widths = c(6,0.8),
	left.legend.padding = 0,
	right.legend.padding = 1,
	top.legend.padding = 0,
	bottom.legend.padding = 0,
	bottom.padding = -1
	);

save(
	cna.data,
	pga,
	file = generate.filename(arguments$project, 'gatk_cna_data', 'RData')
	);

### SAVE SESSION INFO ##############################################################################
save.session.profile(generate.filename('GATKCNASummary','SessionProfile','txt'));
