### plot_snv_tool_summary.R ########################################################################
# Plot overlap of all availabe tools

### FUNCTIONS ######################################################################################
# function to generate a standardized filename
generate.filename <- function(project.stem, file.core, extension, include.date = TRUE) {

        # build up the filename
        file.name <- paste(project.stem, file.core, sep = '_');
        file.name <- paste(file.name, extension, sep = '.');

        if (include.date) {
                file.name <- paste(Sys.Date(), file.name, sep = '_');
                }

        return(file.name);
        }

# function to write session profile to file
save.session.profile <- function(file.name) {

        # open the file
        sink(file = file.name, split = FALSE);

        # write memory usage to file
        cat('### MEMORY USAGE ###############################################################');
        print(proc.time());

        # write sessionInfo to file
        cat("\n### SESSION INFO ###############################################################");
        print(sessionInfo());

        # close the file
        sink();

        }

# function to trim sample IDs
simplify.ids <- function(x) {
	match <- TRUE;
	index <- 1;
	while (match) {
		if (length(unique(sapply(x,function(i) { unlist(strsplit(i,''))[index] } ))) == 1) {
			index <- index + 1;
			} else {
			new.ids <- sapply(x,function(i) { substring(i,index,nchar(i)) } );
			match <- FALSE;
			}
		}
	return(new.ids);
	}

### PREPARE SESSION ################################################################################
# import libraries
library(BoutrosLab.plotting.general);
library(argparse);

# import command line arguments
parser <- ArgumentParser();

parser$add_argument('-p', '--project', type = 'character', help = 'PROJECT name');
parser$add_argument('-o', '--output', type = 'character', help = 'path to output directory');
parser$add_argument('-i', '--input', type = 'character', help = 'path to RData object generated by format_ensemble_mutations.R');

arguments <- parser$parse_args();

### READ DATA ######################################################################################
load(arguments$input);

if (!'combined.data' %in% ls()) {
	stop(paste0("STOP: Object 'combined.data' not found in ", arguments$input));
	}

setwd(arguments$output);

### FORMAT DATA ####################################################################################
all.tools <- c('MuTect2','MuTect','Strelka','VarScan','SomaticSniper','VarDict');
tool.list <- c();
for (tool in all.tools) {
	if (tool %in% colnames(combined.data)) { tool.list <- c(tool.list, tool); }
	}

# do some quick error checks
tool.count <- length(tool.list);

if (tool.count < 2) {
	stop("STOP: Data only available for a single tool - can't plot tool overlap summary.");
	}

# initiate plot data
plot.data <- list();

# get per-tool, per-sample mutation counts
plot.data$per_tool <- aggregate(
	combined.data[,tool.list],
	by = list(Tumor_Sample_Barcode = combined.data$Tumor_Sample_Barcode),
	FUN = sum,
	na.rm = TRUE
	);

# find overlap
plot.data$overlap <- merge(
	aggregate(Hugo_Symbol ~ Tumor_Sample_Barcode + Count, combined.data, length),
	aggregate(Hugo_Symbol ~ Tumor_Sample_Barcode, combined.data, length),
	by = 'Tumor_Sample_Barcode'
	);
colnames(plot.data$overlap) <- c('ID','Overlap','Count','Total');
plot.data$overlap$Overlap <- factor(plot.data$overlap$Overlap, levels = seq(1:tool.count));
plot.data$overlap$Percent <- plot.data$overlap$Count / plot.data$overlap$Total * 100;

# save for future plotting
save(
	plot.data,
	file = generate.filename(arguments$project, 'mutation_overlap', 'RData')
	);

### PLOT DATA ######################################################################################
# grab some parameters
axis.cex <- if (nrow(plot.data$per_tool) <= 30) { 1
	} else if (nrow(plot.data$per_tool) <= 50) { 0.75
	} else if (nrow(plot.data$per_tool) <= 80) { 0.5
	} else { 0 };

# create some plots to summarize overlap
plot.objects <- list();

# plot per-tool counts
for (tool in tool.list) {

	plot.objects[[tool]] <- create.barplot(
		get(tool) ~ Tumor_Sample_Barcode | tool,
		plot.data$per_tool,
		ylab.label = NULL,
		xlab.label = NULL,
		yaxis.cex = 0.8,
		xaxis.lab = rep('',nrow(plot.data$per_tool)),
		yaxis.tck = c(0.5,0),
		xaxis.tck = 0,
		yaxis.fontface = 'plain'
		);
	}

# create a legend (up to max tools used)
overlap.legend <- legend.grob(
	legends = list(
		legend = list(
			colours = rev(default.colours(tool.count,'seq.greenblue')),
			labels = rev(as.character(seq(1:tool.count))),
			title = 'Tool Count'
			)
		),
	title.just = 'left',
	size = 2
	);

# plot overlap
plot.objects[['overlap']] <- create.barplot(
	Percent ~ ID,
	plot.data$overlap,
	groups = plot.data$overlap$Overlap,
	stack = TRUE,
	col = default.colours(tool.count,'seq.greenblue'),
	ylab.label = '% of Total',
	xlab.label = NULL,
	ylimits = c(0,100),
	yat = seq(0,100,20),
	ylab.cex = 1,
	yaxis.cex = 1,
	xaxis.lab = simplify.ids(levels(plot.data$overlap$ID)),
	xaxis.cex = axis.cex,
	yaxis.tck = c(0.5,0),
	xaxis.tck = if (axis.cex == 0) { 0 } else { c(0.5, 0) },
	xaxis.rot = 90,
	yaxis.fontface = 'plain',
	xaxis.fontface = 'plain',
	legend = list(
		right = list(fun = overlap.legend)
		)			
	);

# combine them!
create.multipanelplot(
	plot.objects = plot.objects,
	height = 10,
	width = 8,
	resolution = 200,
	filename = generate.filename(arguments$project, 'mutation_overlap','png'),
	plot.objects.heights = c(rep(1,tool.count),2.5),
	left.legend.padding = 0,
	right.legend.padding = 0,
	top.legend.padding = 0,
	bottom.legend.padding = 0,
	y.spacing = c(rep(-2.5,5),-1),
	ylab.label = paste(
		paste(rep(' ', 50), collapse = ''),
		'Somatic Variant Count (SNVs and INDELs)'
		),
	ylab.cex = 1,
	left.padding = 0,
	ylab.axis.padding = 0,
	bottom.padding = 0,
	top.padding = -1,
	right.padding = 0
	);

### SAVE SESSION INFO ##############################################################################
save.session.profile(generate.filename('SNVToolOverlap','SessionProfile','txt'));
