### plot_viral_counts.R ############################################################################
# Plot viral counts as detected by FusionCatcher.
# INPUT:
#	- species x patient matrix (output by collect_fusioncatcher_output.R)

### FUNCTIONS ######################################################################################
# function to generate a standardized filename
generate.filename <- function(project.stem, file.core, extension, include.date = TRUE) {

	# build up the filename
	file.name <- paste(project.stem, file.core, sep = '_');
	file.name <- paste(file.name, extension, sep = '.');

	if (include.date) {
		file.name <- paste(Sys.Date(), file.name, sep = '_');
		}

	return(file.name);
	}

# function to write session profile to file
save.session.profile <- function(file.name) {

	# open the file
	sink(file = file.name, split = FALSE);

	# write memory usage to file
	cat('### MEMORY USAGE ###############################################################');
	print(proc.time());

	# write sessionInfo to file
	cat("\n### SESSION INFO ###############################################################");
	print(sessionInfo());

	# close the file
	sink();

	}

### PREPARE SESSION ################################################################################
# import command line arguments
library(argparse);

parser <- ArgumentParser();

parser$add_argument('-p', '--project', type = 'character', help = 'PROJECT name');
parser$add_argument('-o', '--output', type = 'character', help = 'path to output directory');
parser$add_argument('-a', '--arriba', type = 'character',
	help = 'path to sample matrix of viral counts (generated by collect_arriba_output.R)');
parser$add_argument('-f', '--fusioncatcher', type = 'character',
	help = 'path to sample matrix of viral counts (generated by collect_fusioncatcher_output.R)');

arguments <- parser$parse_args();

# import libraries
library(BoutrosLab.plotting.general);
library(xtable);

### READ DATA ######################################################################################
# get data
if (!is.null(arguments$arriba)) {
	arriba.input.data <- read.delim(arguments$arriba, row.names = 1);
	}

if (!is.null(arguments$fusioncatcher)) {
	fuscatch.input.data <- read.delim(arguments$fusioncatcher, row.names = 1);
	}

if (is.null(arguments$arriba) & is.null(arguments$fusioncatcher)) {
	stop('ERROR: No inputs provided. Please provide path to output from Arriba and/or fusionCatcher.');
	}

# create (if necessary) and move to output directory
if (!dir.exists(arguments$output)) {
	dir.create(arguments$output);
	}

setwd(arguments$output);

### FORMAT DATA ####################################################################################
all.samples <- list();
all.species <- list();
filtered.data <- list();
formatted.data <- list();

# write function to format species name
format.species <- function(i, type = 'id') {
	i <- gsub('complete_genome','', i); 	# remove sequence type
	while (substr(i,nchar(i),nchar(i)) %in% c(',','_','-',' ')) {
		i <- substr(i, 0, nchar(i)-1);
		}
	j <- c('id' = NA, 'name' = NA);
	j['id'] <- substr(i,0,9);				# species accession id
	i <- unlist(strsplit(i,'_'));
	j['name'] <- paste(i[3:length(i)], collapse = ' ');	# species name
	return(j[type]);
	}

# start with fusioncatcher data
if (!is.null(arguments$fusioncatcher)) {

	# collect list of all (ordered) samples
	all.samples[['FusionCatcher']] <- colnames(fuscatch.input.data);
	all.samples[['FusionCatcher']] <- gsub('\\.','-',all.samples[['FusionCatcher']]);
	
	# filter data
	input.data <- fuscatch.input.data[grepl('_complete_genome', rownames(fuscatch.input.data)),];
	filtered.data[['FusionCatcher']] <- input.data;

	species.counts <- data.frame(
		Species = sapply(rownames(input.data), format.species),
		FullName = sapply(rownames(input.data), format.species, type = 'name'),
		Count = apply(input.data,1,function(i) { length(i[which(i > 1)]) })
		);
	rownames(species.counts) <- rownames(input.data);
	all.species[['FusionCatcher']] <- species.counts;
	
	plot.data <- input.data[which(species.counts$Count > 1),];

	formatted.data[['FusionCatcher']] <- plot.data;
	}

# now do arriba data
if (!is.null(arguments$arriba)) {

	# collect list of all (ordered) samples
	all.samples[['Arriba']] <- colnames(arriba.input.data);
	all.samples[['Arriba']] <- gsub('\\.','-',all.samples[['Arriba']]);

	# filter data
	input.data <- arriba.input.data[grepl('complete_genome', rownames(arriba.input.data)),];
	filtered.data[['Arriba']] <- input.data;

	species.counts <- data.frame(
		Species = sapply(rownames(input.data), format.species),
		FullName = sapply(rownames(input.data), format.species, type = 'name'),
		RPKM = apply(input.data,1,function(i) { length(i[!is.na(i)]) })
		);
	rownames(species.counts) <- rownames(input.data);
	all.species[['Arriba']] <- species.counts;

	plot.data <- input.data[which(species.counts$RPKM > 1),];

	formatted.data[['Arriba']] <- plot.data;
	}

### PLOT DATA ######################################################################################
# plot results for each tool
for (tool in names(formatted.data)) {

	plot.data <- merge(
		all.species[[tool]],
		formatted.data[[tool]],
		by = 'row.names'
		);
	rownames(plot.data) <- plot.data$FullName;
	colnames(plot.data) <- gsub('\\.','-',colnames(plot.data));
	plot.data <- plot.data[,all.samples[[tool]]];

	# grab some parameters
	axis.cex <- if (ncol(plot.data) <= 30) { 1
		} else if (ncol(plot.data) <= 50) { 0.75
		} else if (ncol(plot.data) <= 80) { 0.5
		} else if (ncol(plot.data) <= 100) { 0
		} else { 0 };

	# create heatmap
	create.heatmap(
		log10(plot.data),
		cluster.dimensions = 'none',
		same.as.matrix = TRUE,
		yaxis.lab = NA,
		xaxis.lab = NA, #rep('', nrow(plot.data)),
		yaxis.cex = 0.8,
		xaxis.cex = axis.cex,
		xaxis.tck = 0,
		yaxis.tck = 0.2,
		yaxis.fontface = 'plain',
		xaxis.fontface = 'plain',
		axes.lwd = 1,
		print.colour.key = TRUE,
		fill.colour = 'white',
		colour.scheme = c('white','black'),
		colourkey.cex = 1,
		height = if (nrow(plot.data) > 10) { 7 } else { 5 },
		width = 10,
		resolution = 200,
		filename = generate.filename(arguments$project,
			paste0(tool, '_viral_rna_landscape'),'png')
		);
	}

save(
	filtered.data,
	all.species,
	file = generate.filename(arguments$project, 'viral_data', 'RData')
	);

### LATEX ##########################################################################################
# initiate file
tex.file <- 'viral_summary.tex';
write("\\section{Viral Detection}", file = tex.file);

for (tool in names(formatted.data)) {

	write(paste0(tool,":"), file = tex.file, append = TRUE);

	# find top variably expressed genes
	summary.metrics <- data.frame(
		N.samples = apply(formatted.data[[tool]],1,function(i) { length(i[which(i > 0)]) }),
		Median = apply(formatted.data[[tool]],1,median, na.rm = TRUE)
		);

	summary.metrics <- merge(
		all.species[[tool]][,1:2],
		summary.metrics[which(summary.metrics$N.samples > 1),],
		by = 'row.names'
		);

	# write some captions
	if (tool == 'FusionCatcher') {
		plot.caption <- "Summary of viral RNA within the tumour sample as detected by FusionCatcher. Any species detected in at least two samples are shown. Values are log$_{10}$ viral counts.";
		table.caption <- "Summary of viral RNA within the tumour sample as detected by FusionCatcher. Any species with $>$1 count detected in $>$1 sample are shown."
		} else if (tool == 'Arriba') {
		plot.caption <- "Summary of viral RNA expression within the tumour sample as detected by Arriba. Any species detected in at least two samples are shown. Values are log$_{10}$ RPKM.";
		table.caption <- "Summary of viral RNA expression within the tumour sample as detected by Arriba. Any species detected in at least two samples are shown."; 
		} else {
		plot.caption <- '';
		table.caption <- '';
		}

	# full expression profile
	write("\\begin{figure}[h!]", file = tex.file, append = TRUE);
	write("\\begin{center}", file = tex.file, append = TRUE);
	write(paste0(
		"\\includegraphics[width=0.9\\textwidth]{",
		getwd(), '/',
		generate.filename(arguments$project, paste0(tool, '_viral_rna_landscape'),'png'), '}'
		), file = tex.file, append = TRUE);
	write("\\end{center}", file = tex.file, append = TRUE);
	write(paste0(
		"\\caption{", plot.caption, "}"
		), file = tex.file, append = TRUE);
	write("\\end{figure}\n", file = tex.file, append = TRUE);

	if (nrow(summary.metrics) > 0) {
#		write("\\pagebreak\n", file = tex.file, append = TRUE);
		print(
			xtable(
				summary.metrics[1:min(nrow(summary.metrics),10),-1],
				digits = 1,
				caption = table.caption
				),
			file = tex.file,
			include.rownames = FALSE,
			table.placement = 'h!',
			append = TRUE
			);
		write("\\pagebreak\n", file = tex.file, append = TRUE);
		}
	}

### SAVE SESSION INFO ##############################################################################
save.session.profile(generate.filename('VirualSummary','SessionProfile','txt'));
