### plot_viral_counts.R ############################################################################
# Plot viral counts as detected by FusionCatcher.
# INPUT:
#	- species x patient matrix (output by collect_fusioncatcher_output.R)

### FUNCTIONS ######################################################################################
# function to generate a standardized filename
generate.filename <- function(project.stem, file.core, extension, include.date = TRUE) {

	# build up the filename
	file.name <- paste(project.stem, file.core, sep = '_');
	file.name <- paste(file.name, extension, sep = '.');

	if (include.date) {
		file.name <- paste(Sys.Date(), file.name, sep = '_');
		}

	return(file.name);
	}

# function to write session profile to file
save.session.profile <- function(file.name) {

	# open the file
	sink(file = file.name, split = FALSE);

	# write memory usage to file
	cat('### MEMORY USAGE ###############################################################');
	print(proc.time());

	# write sessionInfo to file
	cat("\n### SESSION INFO ###############################################################");
	print(sessionInfo());

	# close the file
	sink();

	}

### PREPARE SESSION ################################################################################
# import command line arguments
library(argparse);

parser <- ArgumentParser();

parser$add_argument('-p', '--project', type = 'character', help = 'PROJECT name');
parser$add_argument('-o', '--output', type = 'character', help = 'path to output directory');
parser$add_argument('-v', '--viral_counts', type = 'character',
	help = 'path to sample matrix of viral counts (generated by collect_fusioncatcher_output.R)');

arguments <- parser$parse_args();

# import libraries
library(BoutrosLab.plotting.general);
library(xtable);

### READ DATA ######################################################################################
# get data
if (is.null(arguments$viral_counts)) {
	stop('ERROR: No input counts provided, please provide path to VirusCounts from fusionCatcher.');
	} else {
	input.data <- read.delim(arguments$viral_counts, row.names = 1);
	}

# create (if necessary) and move to output directory
if (!dir.exists(arguments$output)) {
	dir.create(arguments$output);
	}

setwd(arguments$output);

### FORMAT DATA ####################################################################################
# collect list of all (ordered) samples
all.samples <- colnames(input.data);
all.samples <- gsub('\\.','-',all.samples);

# filter data
input.data <- input.data[grepl('_complete_genome', rownames(input.data)),];
species.counts <- apply(input.data,1,function(i) { length(i[which(i > 1)]) });
plot.data <- input.data[which(species.counts > 1),];

rownames(plot.data) <- gsub('_complete_genome','',rownames(plot.data));
colnames(plot.data) <- gsub('\\.','-',colnames(plot.data));

rownames(plot.data) <- as.character(sapply(rownames(plot.data),function(i) {
	i <- sub(',$|_$','',i); # removes trailing , or _
	i <- gsub('_',' ', i); # replace _ with spaces
	i <- sub(' ', '_', i); # replace first _ (NC_####.#)
	return(i);
	}));

### PLOT DATA ######################################################################################
# grab some parameters
axis.cex <- if (ncol(plot.data) <= 30) { 1
	} else if (ncol(plot.data) <= 50) { 0.75
	} else if (ncol(plot.data) <= 80) { 0.5
	} else if (ncol(plot.data) <= 100) { 0
	} else { 0 };

# create heatmap
create.heatmap(
	log10(plot.data),
	cluster.dimensions = 'none',
	same.as.matrix = TRUE,
	yaxis.lab = NA,
	xaxis.lab = NA, #rep('', nrow(plot.data)),
	yaxis.cex = 0.8,
	xaxis.cex = axis.cex,
	xaxis.tck = 0,
	yaxis.tck = 0.2,
	yaxis.fontface = 'plain',
	xaxis.fontface = 'plain',
	axes.lwd = 1,
	print.colour.key = TRUE,
	fill.colour = 'white',
	colour.scheme = c('white','black'),
	colourkey.cex = 1,
	height = 8,
	width = 10,
	resolution = 200,
	filename = generate.filename(arguments$project, 'viral_rna_landscape','png')
	);

save(
	input.data,
	species.counts,
	file = generate.filename(arguments$project, 'expression_data', 'RData')
	);

# find top variably expressed genes
summary.metrics <- data.frame(
	N.samples = apply(plot.data,1,function(i) { length(i[which(i > 1)]) }),
	Median = apply(plot.data,1,median, na.rm = TRUE)
	);

# write some captions
plot.caption <- "Summary of viral RNA within the tumour sample as detected by FusionCatcher. Any species detected in at least two samples are shown. Values are log$_{10}$ viral counts.";
table.caption <- "Summary of viral RNA within the tumour sample as detected by FusionCatcher. Any species with $>$1 count detected in $>$1 sample are shown."

# write for latex
write("\\section{Viral Detection}", file = 'viral_summary.tex');

if (nrow(plot.data) > 0) {

	# full expression profile
	write("\\begin{figure}[h!]", file = 'viral_summary.tex', append = TRUE);
	write("\\begin{center}", file = 'viral_summary.tex', append = TRUE);
	write(paste0(
		"\\includegraphics[width=0.9\\textwidth]{",
		getwd(), '/',
		generate.filename(arguments$project, 'viral_rna_landscape','png'), '}'
		), file = 'viral_summary.tex', append = TRUE);
	write("\\end{center}", file = 'viral_summary.tex', append = TRUE);
	write(paste0(
		"\\caption{", plot.caption, "}"
		), file = 'viral_summary.tex', append = TRUE);
	write("\\end{figure}\n", file = 'viral_summary.tex', append = TRUE);

	if (nrow(summary.metrics[which(summary.metrics$N.samples > 1),]) > 0) {
		write("\\pagebreak\n", file = 'viral_summary.tex', append = TRUE);
		print(
			xtable(
				summary.metrics[which(summary.metrics$N.samples > 1),],
				digits = 1,
				caption = table.caption
				),
			file = 'viral_summary.tex',
			include.rownames = FALSE,
			table.placement = 'h!',
			append = TRUE
			);
		}

	} else {
	write("No viral DNA detected by Fusioncatcher.", file = 'viral_summary.tex');
	}

### SAVE SESSION INFO ##############################################################################
save.session.profile(generate.filename('VirualSummary','SessionProfile','txt'));
