### plot_expression_summary.R ######################################################################
# Plot RNA-abundance landscape.
# INPUT:
#	- gene-wise expression values (output by collect_rsem_output.R)

### FUNCTIONS ######################################################################################
# function to generate a standardized filename
generate.filename <- function(project.stem, file.core, extension, include.date = TRUE) {

	# build up the filename
	file.name <- paste(project.stem, file.core, sep = '_');
	file.name <- paste(file.name, extension, sep = '.');

	if (include.date) {
		file.name <- paste(Sys.Date(), file.name, sep = '_');
		}

	return(file.name);
	}

# function to write session profile to file
save.session.profile <- function(file.name) {

	# open the file
	sink(file = file.name, split = FALSE);

	# write memory usage to file
	cat('### MEMORY USAGE ###############################################################');
	print(proc.time());

	# write sessionInfo to file
	cat("\n### SESSION INFO ###############################################################");
	print(sessionInfo());

	# close the file
	sink();

	}

### PREPARE SESSION ################################################################################
# import libraries
library(xtable);
library(BoutrosLab.plotting.general);
library(argparse);

# import command line arguments
parser <- ArgumentParser();

parser$add_argument('-p', '--project', type = 'character', help = 'PROJECT name');
parser$add_argument('-o', '--output', type = 'character', help = 'path to output directory');
parser$add_argument('-r', '--rsem', type = 'character', help = 'path to gene by sample matrix of expression values (generated by collect_rsem_output.R)');

arguments <- parser$parse_args();

### READ DATA ######################################################################################
# get data
input.data <- read.delim(arguments$rsem);

# move to output directory
setwd(arguments$output);

### FORMAT DATA ####################################################################################
# collect list of all (ordered) samples
all.samples <- colnames(input.data)[3:ncol(input.data)];
all.samples <- gsub('\\.','-',all.samples);

# split input data
anno.data <- input.data[,1:2];
plot.data <- input.data[,3:ncol(input.data)];

rownames(plot.data) <- input.data$GeneID;
colnames(plot.data) <- gsub('\\.','-', colnames(plot.data));

# do some minor filtering to remove genes with no variation across the cohort
na.counts <- apply(plot.data,1,function(i) { length(i[is.na(i)]) } );
remove.genes <- names(na.counts)[which(na.counts > ncol(plot.data)*0.6)];

plot.data <- plot.data[!rownames(plot.data) %in% remove.genes,];

gene.variances <- apply(plot.data,1,var,na.rm = TRUE);
plot.data <- plot.data[which(gene.variances > 1),];

### PLOT DATA ######################################################################################
# grab some parameters
axis.cex <- if (ncol(plot.data) <= 30) { 1
	} else if (ncol(plot.data) <= 50) { 0.75
	} else if (ncol(plot.data) <= 80) { 0.5
	} else if (ncol(plot.data) <= 100) { 0
	} else { 0 };

# create heatmap
create.heatmap(
	plot.data,
	cluster.dimensions = 'rows',
	yaxis.lab = NA,
	xaxis.lab = rep('', nrow(plot.data)),
	yaxis.cex = axis.cex,
	xaxis.tck = 0,
	yaxis.tck = 0.2,
	yaxis.fontface = 'plain',
	axes.lwd = 1,
	print.colour.key = TRUE,
	fill.colour = 'grey70',
	at = seq(-5,15,0.1),
	colour.scheme = c('darkorchid2','white','green'),
	colourkey.cex = 1,
	height = 8,
	width = 10,
	resolution = 200,
	filename = generate.filename(arguments$project, 'rna_landscape','png')
	);

# filter again to top 90th quantile
threshold <- quantile(gene.variances, p = 0.99);
filtered.plot.data <- plot.data[names(gene.variances[gene.variances >= threshold]),];

if (any(is.na(filtered.plot.data))) {
	tmp <- apply(filtered.plot.data,1,median,na.rm = TRUE);
	this.order <- names(sort(tmp));
	filtered.plot.data <- filtered.plot.data[this.order,];
	}

create.heatmap(
	filtered.plot.data,
	cluster.dimensions = if (any(is.na(filtered.plot.data))) { 'rows' } else { 'both' },
	yaxis.lab = NA,
	xaxis.lab = rep('', nrow(filtered.plot.data)),
	yaxis.cex = axis.cex,
	xaxis.tck = 0,
	yaxis.tck = 0.2,
	yaxis.fontface = 'plain',
	axes.lwd = 1,
	print.colour.key = TRUE,
	fill.colour = 'grey70',
	at = seq(-2,10,0.01),
	colour.scheme = c('darkorchid2','white','green'),
	colourkey.labels.at = seq(-2,10,2),
	colourkey.cex = 1,
	height = 8,
	width = 10,
	resolution = 200,
	filename = generate.filename(arguments$project, 'rna_landscape_top','png')
	);

save(
	input.data,
	gene.variances,
	threshold,
	file = generate.filename(arguments$project, 'expression_data', 'RData')
	);

# find top variably expressed genes
tmp <- plot.data;
tmp$Mean <- apply(plot.data,1,mean);
tmp$Var <- apply(plot.data,1,var);
tmp <- tmp[which(tmp$Mean > 0),];
tmp <- tmp[order(tmp$Var, decreasing = T),];

top.genes <- rownames(tmp)[1:20];
top.gene.data <- plot.data[top.genes,];

summary.metrics <- merge(
	anno.data[anno.data$GeneID %in% top.genes,],
	data.frame(
		Mean = apply(top.gene.data,1,mean),
		Median = apply(top.gene.data,1,median),
		Lower_25 = apply(top.gene.data,1,quantile, p = 0.25),
		Upper_75 = apply(top.gene.data,1,quantile, p = 0.75),
		SD = apply(top.gene.data,1,sd)
		),
	by.x = 'GeneID',
	by.y = 'row.names'
	);

summary.metrics$CV <- summary.metrics$SD / summary.metrics$Mean;

summary.metrics$GeneID <- factor(summary.metrics$GeneID, levels = top.genes);
summary.metrics <- summary.metrics[order(summary.metrics$GeneID),];

# write some captions
full.caption <- "Gene-wise expession profile; values are log$_2$ TPM.";
trimmed.caption <- paste0("Expression profile (log$_2$ TPM) for the top 1\\% most variable genes (variance $\\geq$", round(threshold), ").");

if (any(is.na(filtered.plot.data))) {
	trimmed.caption <- paste(trimmed.caption, 'Genes ordered by median expression.');
	}

# write for latex
write("\\section{RNA Expression}", file = 'expression_summary.tex');

# full expression profile
write("\\begin{figure}[h!]", file = 'expression_summary.tex', append = TRUE);
write("\\begin{center}", file = 'expression_summary.tex', append = TRUE);
write(paste0(
	"\\includegraphics[width=0.9\\textwidth]{",
	getwd(), '/',
	generate.filename(arguments$project, 'rna_landscape','png'), '}'
	), file = 'expression_summary.tex', append = TRUE);
write("\\end{center}", file = 'expression_summary.tex', append = TRUE);
write(paste0(
	"\\caption{", full.caption, "}"
	), file = 'expression_summary.tex', append = TRUE);
write("\\end{figure}\n", file = 'expression_summary.tex', append = TRUE);

# top variant plot
write("\\pagebreak\n\\begin{figure}[h!]", file = 'expression_summary.tex', append = TRUE);
write("\\begin{center}", file = 'expression_summary.tex', append = TRUE);
write(paste0(
	"\\includegraphics[width=0.9\\textwidth]{",
	getwd(), '/',
	generate.filename(arguments$project, 'rna_landscape_top','png'), '}'
	), file = 'expression_summary.tex', append = TRUE);
write("\\end{center}", file = 'expression_summary.tex', append = TRUE);
write(paste0(
	"\\caption{", trimmed.caption, "}"
	), file = 'expression_summary.tex', append = TRUE);
write("\\end{figure}\n\\pagebreak\n", file = 'expression_summary.tex', append = TRUE);

print(
	xtable(
		summary.metrics[,c('Symbol','Lower_25','Median','Upper_75','CV')],
		caption = 'Top 20 most variably expressed genes (genes with mean expression $>$ 0, ordered by decreasing variance) across the cohort. Table shows gene symbol, lower 25th percentile, median and upper 25th percentile of expression values.'
		),
	file = 'expression_summary.tex',
	include.rownames = FALSE,
	table.placement = 'h!',
	append = TRUE
	);

### SAVE SESSION INFO ##############################################################################
save.session.profile(generate.filename('ExpressionSummary','SessionProfile','txt'));
