### write_rna_fusion_summary.R #####################################################################
# Plot RNA fusion summary.
# INPUT:
#	- list of predicted fusions formatted for cbioportal (output by collect_star-fusion_output.R and collect_fusioncatcher_output.R)

### FUNCTIONS ######################################################################################
# function to generate a standardized filename
generate.filename <- function(project.stem, file.core, extension, include.date = TRUE) {

	# build up the filename
	file.name <- paste(project.stem, file.core, sep = '_');
	file.name <- paste(file.name, extension, sep = '.');

	if (include.date) {
		file.name <- paste(Sys.Date(), file.name, sep = '_');
		}

	return(file.name);
	}

# function to write session profile to file
save.session.profile <- function(file.name) {

	# open the file
	sink(file = file.name, split = FALSE);

	# write memory usage to file
	cat('### MEMORY USAGE ###############################################################');
	print(proc.time());

	# write sessionInfo to file
	cat("\n### SESSION INFO ###############################################################");
	print(sessionInfo());

	# close the file
	sink();

	}

### PREPARE SESSION ################################################################################
# import libraries
library(xtable);
library(BoutrosLab.plotting.general);
library(argparse);

# import command line arguments
parser <- ArgumentParser();

parser$add_argument('-p', '--project', type = 'character', help = 'PROJECT name');
parser$add_argument('-o', '--output', type = 'character', help = 'path to output directory');
parser$add_argument('-s', '--starfus', type = 'character', help = 'path to star-fusion output (generated by collect_star-fusion_output.R)');
parser$add_argument('-f', '--fusioncatcher', type = 'character', help = 'path to fusioncatcher output (generated by collect_fusioncatcher_output.R)');

arguments <- parser$parse_args();

### READ DATA ######################################################################################
# get data
if (!is.null(arguments$starfus)) {
	starfusion <- read.delim(arguments$starfus);
	}
if (!is.null(arguments$fusioncatcher)) {
	fusioncatcher <- read.delim(arguments$fusioncatcher);
	}

# move to output directory
setwd(arguments$output);

### FORMAT DATA ####################################################################################
if (!is.null(arguments$starfus) & !is.null(arguments$fusioncatcher)) {

	# merge tables, keeping only those events detected by both methods
	combined.fusions <- merge(
		starfusion[,c('Tumor_Sample_Barcode','Fusion','Method','Frame')],
		fusioncatcher[,c('Tumor_Sample_Barcode','Fusion','Method','Frame')],
		by = c('Tumor_Sample_Barcode','Fusion','Frame')
		);

	combined.fusions <- unique(combined.fusions);

	# collect summary stats
	summary.metrics <- data.frame(
		Method = c('STAR-Fusion','FusionCatcher','Both'),
		Total = c(nrow(starfusion)/2, nrow(fusioncatcher)/2, nrow(combined.fusions)),
		InFrame = c(
			nrow(starfusion[which(starfusion$Frame == 'in-frame'),])/2,
			nrow(fusioncatcher[which(fusioncatcher$Frame == 'in-frame'),])/2,
			nrow(combined.fusions[which(combined.fusions$Frame == 'in-frame'),])
			),
		Frameshift = c(
			nrow(starfusion[which(starfusion$Frame == 'frameshift'),])/2,
			nrow(fusioncatcher[which(fusioncatcher$Frame == 'frameshift'),])/2,
			nrow(combined.fusions[which(combined.fusions$Frame == 'frameshift'),])
			)
		);

	caption <- "Number of fusions detected by STAR-Fusion and Fusioncatcher, and the overlap.";

	} else {
	
		if (!is.null(arguments$starfus)) {

			# collect summary stats
			summary.metrics <- data.frame(
				Method = 'STAR-Fusion',
				Total = nrow(starfusion)/2,
				InFrame = nrow(starfusion[which(starfusion$Frame == 'in-frame'),])/2,
				Frameshift = nrow(starfusion[which(starfusion$Frame == 'frameshift'),])/2
				);

			caption <- "Number of fusions detected by STAR-Fusion.";
			combined.fusions <- starfusion;

			} else if (!is.null(arguments$fusioncatcher)) {

			# collect summary stats
			summary.metrics <- data.frame(
				Method = 'FusionCatcher',
				Total = nrow(fusioncatcher)/2,
				InFrame = nrow(fusioncatcher[which(fusioncatcher$Frame == 'in-frame'),])/2,
				Frameshift = nrow(fusioncatcher[which(fusioncatcher$Frame == 'frameshift'),])/2
				);

			caption <- "Number of fusions detected by FusionCatcher.";
			combined.fusions <- fusioncatcher;
			}
		}

# find any recurrent fusion
fusion.counts <- sort(table(droplevels(combined.fusions$Fusion)));
recurrent.fusions <- names(fusion.counts[which(fusion.counts > 1)]);

combined.fusions <- combined.fusions[order(combined.fusions$Fusion),];

### WRITE DATA #####################################################################################
# write for latex
write("\\section{Fusion Summary}", file = 'fusion_summary.tex');

print(
	xtable(
		summary.metrics,
		digits = 0,
		caption = caption
		),
	file = 'fusion_summary.tex',
	include.rownames = FALSE,
	table.placement = 'h!',
	append = TRUE
	);

if (length(recurrent.fusions) > 0) {
	to.write <- combined.fusions[which(combined.fusions$Fusion %in% recurrent.fusions),1:3];
	colnames(to.write) <- c('Sample','Fusion','Frame');
	print(
		xtable(
			to.write,
			caption = "Fusions detected by both STAR-Fusion and Fusioncatcher in multiple samples."
			),
		file = 'fusion_summary.tex',
		include.rownames = FALSE,
		table.placement = 'h!',
		append = TRUE
		);
	} else {
	write("No recurrent fusions detected.", file = 'fusion_summary.tex', append = TRUE);
	}

### SAVE SESSION INFO ##############################################################################
save.session.profile(generate.filename('FusionSummary','SessionProfile','txt'));
