### write_rna_fusion_summary.R #####################################################################
# Plot RNA fusion summary.
# INPUT:
#	- list of predicted fusions formatted for cbioportal (output by collect_star-fusion_output.R and collect_fusioncatcher_output.R)

### FUNCTIONS ######################################################################################
# function to generate a standardized filename
generate.filename <- function(project.stem, file.core, extension, include.date = TRUE) {

	# build up the filename
	file.name <- paste(project.stem, file.core, sep = '_');
	file.name <- paste(file.name, extension, sep = '.');

	if (include.date) {
		file.name <- paste(Sys.Date(), file.name, sep = '_');
		}

	return(file.name);
	}

# function to write session profile to file
save.session.profile <- function(file.name) {

	# open the file
	sink(file = file.name, split = FALSE);

	# write memory usage to file
	cat('### MEMORY USAGE ###############################################################');
	print(proc.time());

	# write sessionInfo to file
	cat("\n### SESSION INFO ###############################################################");
	print(sessionInfo());

	# close the file
	sink();

	}

### PREPARE SESSION ################################################################################
# import command line arguments
library(argparse);

parser <- ArgumentParser();

parser$add_argument('-p', '--project', type = 'character', help = 'PROJECT name');
parser$add_argument('-o', '--output', type = 'character', help = 'path to output directory');
parser$add_argument('-a', '--arriba', type = 'character',
	help = 'path to arriba output (generated by collect_arriba_output.R)');
parser$add_argument('-s', '--starfus', type = 'character',
	help = 'path to star-fusion output (generated by collect_star-fusion_output.R)');
parser$add_argument('-f', '--fusioncatcher', type = 'character',
	help = 'path to fusioncatcher output (generated by collect_fusioncatcher_output.R)');
parser$add_argument('-m', '--mavis', type = 'character',
	help = 'path to mavis output (generated by collect_mavis_output.R)');

arguments <- parser$parse_args();

# import libraries
library(BoutrosLab.plotting.general);
library(xtable);

### READ DATA ######################################################################################
# get data
template.df <- as.data.frame(matrix(ncol = 4));
colnames(template.df) <- c('Tumor_Sample_Barcode','Fusion','Method','Frame');

tool.list <- c();

if (!is.null(arguments$arriba)) {
	arriba <- read.delim(arguments$arriba);
	tool.list <- c(tool.list, 'arriba');
	} else { arriba <- template.df; }
if (!is.null(arguments$starfus)) {
	starfusion <- read.delim(arguments$starfus);
	tool.list <- c(tool.list, 'starfusion');
	} else { starfusion <- template.df; }
if (!is.null(arguments$fusioncatcher)) {
	fusioncatcher <- read.delim(arguments$fusioncatcher);
	tool.list <- c(tool.list, 'fusioncatcher');
	} else { fusioncatcher <- template.df; }
if (!is.null(arguments$mavis)) {
	mavis <- read.delim(arguments$mavis);
	}

# create (if necessary) and move to output directory
if (!dir.exists(arguments$output)) {
	dir.create(arguments$output);
	}

setwd(arguments$output);

### FORMAT DATA ####################################################################################
arriba <- unique(arriba[,c('Tumor_Sample_Barcode','Fusion','Method','Frame')]);
starfusion <- unique(starfusion[,c('Tumor_Sample_Barcode','Fusion','Method','Frame')]);
fusioncatcher <- unique(fusioncatcher[,c('Tumor_Sample_Barcode','Fusion','Method','Frame')]);

# merge tables, keeping only those events detected by both methods
combined.fusions <- merge(
	arriba,
	merge(
		starfusion,
		fusioncatcher,
		by = c('Tumor_Sample_Barcode','Fusion','Frame'),
		all = TRUE
		),
	by = c('Tumor_Sample_Barcode','Fusion','Frame'),
	all = TRUE
	);

combined.fusions$Tools <- apply(
	combined.fusions[,grepl('Method', colnames(combined.fusions))],
	1,
	function(i) { 
		i <- na.omit(i);
		return(paste(i, collapse = ';'));
		}
	);

if (any(is.na(combined.fusions$Tools))) { 
	combined.fusions <- combined.fusions[!is.na(combined.fusions$Tools),];
	}

combined.fusions <- unique(combined.fusions[,!grepl('Method', colnames(combined.fusions))]);

# collect summary stats
summary.metrics <- data.frame(
	Method = c('Arriba','STAR-Fusion','FusionCatcher','Unique'),
	Total = c(
		length(unique(na.omit(arriba$Fusion))),
		length(unique(na.omit(starfusion$Fusion))),
		length(unique(na.omit(fusioncatcher$Fusion))),
		length(unique(na.omit(combined.fusions$Fusion)))
		),
	InFrame = c(
		nrow(arriba[which(arriba$Frame == 'inframe'),]),
		nrow(starfusion[which(starfusion$Frame == 'inframe'),]),
		nrow(fusioncatcher[which(fusioncatcher$Frame == 'inframe'),]),
		nrow(combined.fusions[which(combined.fusions$Frame == 'inframe'),])
		),
	Frameshift = c(
		nrow(arriba[which(arriba$Frame == 'frameshift'),]),
		nrow(starfusion[which(starfusion$Frame == 'frameshift'),]),
		nrow(fusioncatcher[which(fusioncatcher$Frame == 'frameshift'),]),
		nrow(combined.fusions[which(combined.fusions$Frame == 'frameshift'),])
		)
	);

caption <- "Number of fusions detected by TOOLS, and the overlap.";
caption <- sub('TOOLS', paste(tool.list, collapse = ', '), caption);

# find any recurrently-detected fusion (multiple tools)
if (length(tool.list) > 1) {
	recurrent.hits <- aggregate(
		Tumor_Sample_Barcode ~ Fusion + Frame,
		combined.fusions[grepl(';', combined.fusions),],
		length
		);
	} else {
	# find recurrent events (across samples)
	recurrent.hits <- aggregate(
		Tumor_Sample_Barcode ~ Fusion + Frame,
		combined.fusions,
		length
		);
	}

colnames(recurrent.hits) <- c('Fusion','Frame','N.samples');
recurrent.hits <- recurrent.hits[order(recurrent.hits$N.samples, decreasing = TRUE),];

# add Mavis status if available
if (!is.null(arguments$mavis)) {

	mavis$library <- gsub('-wxs|-wgs|-rna', '', mavis$library);

	combined.fusions$Validation <- NA;
	for (i in 1:nrow(combined.fusions)) {
		smp <- as.character(combined.fusions[i,]$Tumor_Sample_Barcode);
		fusion <- as.character(combined.fusions[i,]$Fusion);

		mavis.idx <- which(mavis$library == smp & mavis$Fusion == fusion);
		if (length(mavis.idx) > 0) { combined.fusions[i,]$Validation <- 'mavis'; }
		}

	mavis.summary <- mavis;
	if (nrow(mavis.summary) > 40) {
		mavis.summary <- mavis.summary[!grepl('None',mavis.summary$Fusion),];
		}
	if (nrow(mavis.summary) > 40) {
		mavis.summary$evidence <- apply(
			mavis.summary[,c('spanning_reads','linking_split_reads','break1_split_reads','break2_split_reads')],
			1, function(x) { sum(sapply(x,
				function(i) max(as.numeric(unlist(strsplit(as.character(i),';'))))))
				}
			);
		mavis.summary$n.tools <- sapply(mavis.summary$tools, function(i) {
			length(unlist(strsplit(i,';'))) } );
		mavis.summary <- mavis.summary[order(-mavis.summary$n.tools, -mavis.summary$evidence),];
		mavis.summary <- mavis.summary[1:40,];
		}
	mavis.summary <- mavis.summary[,c('library','event_type','Fusion','n.tools')];
	mavis.summary <- mavis.summary[order(mavis.summary$Fusion, mavis.summary$library),];
	}

### WRITE DATA #####################################################################################
# write for latex
write("\\section{Fusion Summary}", file = 'fusion_summary.tex');

print(
	xtable(
		summary.metrics,
		digits = 0,
		caption = caption
		),
	file = 'fusion_summary.tex',
	include.rownames = FALSE,
	table.placement = 'h!',
	append = TRUE
	);

if (nrow(recurrent.hits) > 0) {
	to.write <- recurrent.hits[1:min(nrow(recurrent.hits),20),];
	print(
		xtable(
			to.write,
			caption = ifelse(length(tool.list) > 1,
				"Fusions detected by multiple tools and in multiple samples.",
				"Fusions detected in multiple samples."
				)
			),
		file = 'fusion_summary.tex',
		include.rownames = FALSE,
		table.placement = 'h!',
		append = TRUE
		);
	} else {
	write("No recurrent fusions detected.", file = 'fusion_summary.tex', append = TRUE);
	}

if (exists('mavis.summary')) {
	write('\\pagebreak', file = 'fusion_summary.tex', append = TRUE);
	print(
		xtable(
			mavis.summary,
			digits = 0,
			caption = 'Fusions validated by Mavis.'
			),
		file = 'fusion_summary.tex',
		include.rownames = FALSE,
		table.placement = 'h!',
		append = TRUE
		);
	}

### SAVE SESSION INFO ##############################################################################
save.session.profile(generate.filename('FusionSummary','SessionProfile','txt'));
