---
project_name: PROJECTNAME
output_dir: /cluster/projects/pughlab/projects/PROJECTNAME/Exome/
sample_type: # optional; can be germline or ctdna
seq_type: exome # must be one of exome, targeted, rna or wgs
seq_center: PMGC
platform: Illumina
flowcell_type: random # one of random or patterned, depends on the instrument used: https://knowledge.illumina.com/instrumentation/general/instrumentation-general-faq-list/000007786
hpc_group:
# reference files
ref_type: hg19
reference: /cluster/tools/data/genomes/human/hg19/iGenomes/Sequence/WholeGenomeFasta/genome.fa
baits_bed: 
targets_bed: 
gnomad: /cluster/projects/pughlab/references/gnomad/gnomad_v2.0.2/Exome/gnomad.exomes.r2.0.2.sites.vcf.gz
dbsnp: /cluster/projects/pughlab/references/dbSNP/GRCh37/b151/dbSNP_GRCh37p13_b151_common_chr.vcf.gz
cosmic: /cluster/projects/pughlab/references/COSMIC/GRCh37/v92/CosmicVariants_full_sorted_chr.vcf.gz
snp6: /cluster/projects/pughlab/references/ASCAT_refs/GRCh37_SNP6.tsv.gz
exclude_regions: /cluster/projects/pughlab/references/Delly/excludeTemplates/human.hg19.excl.tsv
gatk_known_1000g: /cluster/tools/data/genomes/human/hg19/variantcallingdata/1000G_phase1.snps.high_confidence.hg19.vcf 
gatk_known_indels: /cluster/tools/data/genomes/human/hg19/variantcallingdata/1000G_phase1.indels.hg19.vcf
gatk_known_mills: /cluster/tools/data/genomes/human/hg19/variantcallingdata/Mills_and_1000G_gold_standard.indels.hg19.vcf
gatk_hapmap: /cluster/tools/data/genomes/human/hg19/variantcallingdata/hapmap_3.3.hg19.vcf
gatk_omni: /cluster/tools/data/genomes/human/hg19/variantcallingdata/1000G_omni2.5.hg19.vcf
contest_hapmap: /cluster/projects/pughlab/references/hapmap/hg19_population_stratified_af_hapmap_3.3.vcf.gz
svict_gtf: /cluster/projects/pughlab/references/gencode/GRCh37/v36/gencode.v36lift37.annotation.gtf.gz
mutsig_coverage: /cluster/projects/pughlab/references/MutSigCV/exome_full192.coverage.txt
mutsig_covariates: /cluster/projects/pughlab/references/MutSigCV/gene.covariates.txt
mutsig_categories: /cluster/projects/pughlab/references/MutSigCV/mutation_type_dictionary_file.txt
mutsig_refs: /cluster/projects/pughlab/references/MutSigCV/chr_files_hg19
# tool versions
perl_version: 5.30.0
fastqc_version: 0.11.5
bwa_version: 0.7.15
samtools_version: 1.9
picard_version: 2.6.0
sambamba_version: 0.7.0
bedtools_version: 2.27.1
gatk_version: 3.8
gatk_cnv_version: 4.1.8.1
vcftools_version: 0.1.15
mutect_version: 1.1.5
somaticsniper_version: bam-somaticsniper/1.0.5.0 # or SomaticSniper/1.0.4 currently available on h4h
vardict_version: 1.7.0
varscan_version: 2.4.2
python2_version: 2.7.15
strelka_version: 2.9.10
manta_version: 1.6.0
delly_version: 0.8.1
novobreak_version: 1.1
svict_version: 
svict_path: /cluster/projects/pughlab/bin/svict
ichor_cna_version: 0.3.2
ascat_r_version: 4.1.0
panelcnmops_version: 1.14.0
pindel_version: 0.2.5b8
mavis_version: 2.2.5
cpsr_version: 0.6.1
pcgr_version: 0.9.1
vcf2maf_version: 1.6.17 
msi_sensor_version: msisensor-pro/1.2.0
r_version: 4.1.0
mutsigcv_version: 1.4
mcr_path: /cluster/tools/software/MCR/8.1/v81
# tool specific parameters
fastqc:
    run: Y
    parameters:
        fastqc:
            mem: 2G
            time: '24:00:00'
bwa:
    run: Y
    aligner: bwamem
    reference: /cluster/tools/data/genomes/human/hg19/bwa/ucsc.hg19.fasta
    parameters:
        bwa:
            mem:
                normal: 8G
                tumour: 8G
            time:
                normal: '24:00:00'
                tumour: '48:00:00'
        sort:
            mem:
                normal: 4G
                tumour: 4G
            time:
                normal: '24:00:00'
                tumour: '48:00:00'
        index:
            mem:
                normal: 2G
                tumour: 2G
            time:
                normal: '05:00:00'
                tumour: '05:00:00'
        merge:
            tool: 'picard' # or sambamba
            mark_dup: Y
            n_cpus: 1 # or more for sambamba
            java_mem:
                normal: 7g
                tumour: 11g
            mem:
                normal: 8G
                tumour: 12G
            time:
                normal: '48:00:00'
                tumour: '48:00:00'
gatk:
    run: Y
    parameters:
        target_creator:
            java_mem: 5g
            mem: 6G
            time: '48:00:00'
        realign:
            java_mem: 3g
            mem: 4G
            time: '72:00:00'
        bqsr:
            java_mem: 11g
            mem: 12G
            time:
                normal: '48:00:00'
                tumour: '72:00:00'
        recalibrate:
            java_mem: 11g
            mem: 12G
            time:
                normal: '48:00:00'
                tumour: '72:00:00'
bamqc:
    run: Y
    parameters:
        contest: # no longer necessary as gatk's calculateContamination is now included in the other 'qc' steps
            run: N
            threshold: '3.0'
            java_mem: 1g
            mem: 2G
            time: '24:00:00'
        qc:
            java_mem: 3g
            mem: 4G
            time: '48:00:00'
        coverage:
            java_mem: 3g
            mem: 4G
            time: '48:00:00'
            n_cpus: 2
        callable_bases:
            min_depth:
                tumour: 20
                normal: 15
            mem: 4G
            time: '48:00:00'
haplotype_caller:
    run: Y
    chromosomes:
    parameters:
        haplotype_call:
            java_mem: 3g
            mem: 4G
            time: '72:00:00'
        combine_gvcfs:
            java_mem: 5g
            mem: 6G
            time: '5-00:00:00'
        genotype_gvcfs:
            java_mem: 5g
            mem: 6G
            time: '5-00:00:00'
        vqsr:
            java_mem: 7g
            mem: 8G
            time: '24:00:00'
        apply_vqsr:
            java_mem: 1g
            mem: 2G
            time: '24:00:00'
        hard_filtering:
            run: N
            java_mem: 1g
            mem: 2G
            time: '24:00:00' 
        filter_recalibrated:
            mem: 2G
            time: '24:00:00'
        run_vcf2maf: N
        cpsr:
            known_positions: /cluster/projects/pughlab/references/CPSR/PCA_pathVar_integrated_filtered_adjusted_WITH_FANCI_hg19.tsv 
            mem: 4G
            time: '24:00:00'
annotate:
    vcf2maf_path: # /cluster/projects/pughlab/bin/vcf2maf-1.6.17/vcf2maf.pl  ## provide EITHER this or vcf2maf_version above ##
    vep_path: /cluster/tools/software/centos7/vep/98
    vep_data: /cluster/projects/pughlab/references/VEP_cache/98
    filter_vcf: /cluster/projects/pughlab/references/VEP_cache/ExAC_nonTCGA.r1.sites.b37TOhg19.vep.vcf.gz
    buffer_size: 1000
    n_cpus: 4
    mem: 16G
    time: '12:00:00'
mutect:
    run: Y
    pon: /cluster/projects/pughlab/references/panel_of_normals/hg19/mutect_v1.1.5_hg38LFThg19_panel_of_normals_20210330.vcf
    parameters:
        mutect:
            java_mem: 11g
            mem: 12G
            time: '4-00:00:00'
        filter:
            mem: 4G
            time: '12:00:00'
        create_pon:
            minN: 2
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
mutect2:
    run: Y
    pon: /cluster/projects/pughlab/references/panel_of_normals/hg19/mutect2_v3.8_hg38LFThg19_panel_of_normals_20210330.vcf
#    chromosomes: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY
    parameters:
        mutect:
            java_mem: 3g
            mem: 4G
            time: '5-00:00:00' # some WXS can take >14 days to complete
        merge:
            mem: 2G
            time: '12:00:00'
        filter:
            mem: 1G
            time: '12:00:00'
        create_pon:
            minN: 2
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
manta:
    run: Y
    parameters:
        manta:
            mem: 8G
            time: '24:00:00'
strelka:
    run: Y
    pon: /cluster/projects/pughlab/references/panel_of_normals/hg19/strelka_v2.9.10_hg38LFThg19_panel_of_normals_20210330.vcf
    parameters:
        strelka:
            mem: 8G
            time: '24:00:00'
        filter:
            mem: 2G
            time: '12:00:00'
        create_pon:
            minN: 2
            java_mem: 3g
            mem: 4G
            time: '96:00:00'
varscan:
    run: Y
    pon: /cluster/projects/pughlab/references/panel_of_normals/hg19/varscan_v2.4.2_hg38LFThg19_panel_of_normals_20210330.vcf
#    chromosomes: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY
    parameters:
        varscan:
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
        sequenza:
            cancer_type_prior: all
            ploidy_priors: /cluster/projects/pughlab/src/sequenza_wrapper/PANCAN_ASCAT_ploidy_prob.Rdata
            mem: 6G
            time: '24:00:00'
        filter:
            mem: 1G
            time: '12:00:00'
        create_pon:
            minN: 2
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
somaticsniper:
    run: Y
    pon:
    parameters:
        somaticsniper:
            mem: 4G
            time: '24:00:00'
        pileup:
            mem: 4G
            time: '24:00:00'
        readcount:
            mem: 1G
            time: '24:00:00'
        filter:
            mem: 1G
            time: '24:00:00'
vardict:
    run: Y
    intervals: /cluster/projects/pughlab/references/intervals/whole_genome_intervals/GRCh37_wgs_intervals_for_vardict_no_centromere.txt # only for WGS
    pon: /cluster/projects/pughlab/references/panel_of_normals/hg19/vardict_v1.7.0_hg38LFThg19_panel_of_normals_20210330.vcf
    parameters:
        vardict:
            # vardict_wgs requires slightly higher mem (~16G) and more time (min 32 hours)
            mem: 12G
            java_mem: 11g
            time: '24:00:00'
        test_somatic:
            mem: 16G
            time: '24:00:00'
        filter:
            mem: 1G
            time: '12:00:00'
        create_pon:
            minN: 2
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
pindel:
    run: Y
    chromosomes:
    parameters:
        pindel:
            mem: 6G
            time: '48:00:00'
            n_cpu: 1
        convert:
            filter_depth: 5
            mem: 2G
            time: '24:00:00'
gatk_cnv:
    run: Y
    chromosomes:
    parameters:
        readcounts:
            mem: 1G
            time: '12:00:00'
        create_pon:
            java_mem: 5g
            mem: 6G
            time: '24:00:00'
        denoise:
            java_mem: 7g
            mem: 8G
            time: '24:00:00'
        allele_counts:
            java_mem: 7g
            mem: 8G
            time: '24:00:00'
        model:
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
delly:
    run: Y
    parameters:
        call:
            mem: 8G
            time: '72:00:00'
        genotype:
            mem: 6G
            time: '48:00:00'
        merge:
            mem: 2G
            time: '24:00:00'
        filter:
            mem: 2G
            time: '12:00:00'
novobreak:
    run: Y
    chromosomes:
    parameters:
        novobreak:
            mem: 40G
            time: '24:00:00'
            n_cpus: 10
        group_reads:
            mem: 40G
            time: '24:00:00'
        postprocess:
            mem: 12G
            time: '5-00:00:00'
            n_cpus: 4
        filter:
            mem: 4G
            time: '12:00:00'
svict:
    run: N # only for ctDNA (targeted panel)
    parameters:
        svict:
            mem: 16G
            time: '24:00:00'
panelcn_mops:
    run: Y # only for targeted panel
    pon: # ignored if create_pon:run:Y
    parameters:
        run_cohort: N
        create_pon:
            run: N
            mem: 2G
            time: '24:00:00'
        cn_mops:
            mem: 4G
            time: '24:00:00'
ichor_cna:
    run: N # ideal for low-pass WGS
    pon: 
    parameters:
        readcounter:
            mem: 2G
            time: '24:00:00'
        ichor_cna:
            mem: 2G
            time: '24:00:00'
ascat:
    run: N # only for WGS
    parameters:
        ascat_lib_path: '/cluster/projects/pughlab/src/r_lib/library/4.1/'
        ascat:
            mem: 4G
            time: '24:00:00'
            n_cpus: 1
mavis:
    run: Y
    mem: 4G # increase this is patient has multiple tumours and/or many SV callers were run
    mavis_mem_limit: # in Mb, default is 16000; increase if individual steps are running out of memory
    mavis_time_limit: # in seconds, default is 57600 ; increase if individual steps are running out of time
    mavis_max_jobs: # maximum number of jobs to submit at a time; decrease if hitting slurm job cap
#    mavis_queue: # if the above mavis_mem_limit or mavis_time_limit require a non-default queue/partition
    mavis_annotations: /cluster/projects/pughlab/references/MAVIS_ref_hg19/ensembl69_hg19_annotations.json
    mavis_masking: /cluster/projects/pughlab/references/MAVIS_ref_hg19/hg19_masking.tab
    mavis_dgv_anno: /cluster/projects/pughlab/references/MAVIS_ref_hg19/dgv_hg19_variants.tab
    mavis_cytoband: /cluster/projects/pughlab/references/MAVIS_ref_hg19/cytoBand.txt
    mavis_draw_fusions_only: false
    mavis_aligner: 'bwa mem'
msi_sensor:
    run: Y
    parameters:
        scan:
            mem: 1G
            time: '04:00:00'
        baseline: # only required if tumour-only samples are also present
            mem: 4G
            time: '5-00:00:00'
        sensor: # some WGS require up to 36G, but most (WXS/WGS/targeted) are fine with 4G
            mem: 4G
            time: '24:00:00'
summarize_steps:
    lib_path: '/cluster/projects/pughlab/src/r_lib/library/4.1/'
    run_cosmic_sbs: # note that signatures (path) takes priority over cosmic_version
        run: Y
        signatures: #/cluster/projects/pughlab/references/COSMIC/Mutational_Sigatures/COSMIC_v3.2_SBS_GRCh37.txt
        cosmic_version: 3.2 # one of 3.0, 3.1, 3.2, 3.3
    run_mutsig: Y
    run_chord: N
    run_hrdetect: N
