### collect_sequenza_output.R ######################################################################
# Finds and combines output generated by Sequenza (CN segments, cellularity, ploidy)

### FUNCTIONS ######################################################################################
# function to generate a standardized filename
generate.filename <- function(project.stem, file.core, extension, include.date = TRUE) {

	# build up the filename
	file.name <- paste(project.stem, file.core, sep = '_');
	file.name <- paste(file.name, extension, sep = '.');

	if (include.date) {
		file.name <- paste(Sys.Date(), file.name, sep = '_');
		}

	return(file.name);
	}

# function to write session profile to file
save.session.profile <- function(file.name) {

	# open the file
	sink(file = file.name, split = FALSE);

	# write memory usage to file
	cat('### MEMORY USAGE ###############################################################');
	print(proc.time());

	# write sessionInfo to file
	cat("\n### SESSION INFO ###############################################################");
	print(sessionInfo());

	# close the file
	sink();

	}

### PREPARE SESSION ################################################################################
# import libraries
library(GenomicRanges);
library(argparse);

# import command line arguments
parser <- ArgumentParser();

parser$add_argument('-d', '--directory', type = 'character', help = 'path to data directory');
parser$add_argument('-p', '--project', type = 'character', help = 'project name');
parser$add_argument('-g', '--gtf', type = 'character', help = 'annotation gtf (refGene)',
	default = '/cluster/projects/pughlab/references/gencode/GRCh38/gencode.v31.GRCh38.genes.gtf');
parser$add_argument('-t', '--targets', type = 'character', help = 'target intervals',
	default = '/cluster/tools/data/genomes/human/hg38/SureSelect_Human_All_Exon_V5+UTRs_S04380219_Covered_for_bamqc_liftover_hg38.bed');

arguments <- parser$parse_args();

# what's the date?
date <- Sys.Date();

setwd(arguments$directory);

### FORMAT ANNOTATION
# using refGene, indicate genes to keep (coding genes) for gene x patient matrix
refGene <- read.delim(arguments$gtf, header = F, comment.char = '#');

refGene <- droplevels(refGene[which(refGene$V3 == 'gene'),c(1,4,5,9)]);
colnames(refGene) <- c('Chromosome','Start','End','INFO');

refGene <- refGene[grepl('gene_type protein_coding', refGene$INFO),];

gene.widths <- refGene$End - refGene$Start;
refGene <- droplevels(refGene[which(gene.widths > 20),]);

refGene.gr <- GRanges(refGene);

# if provided, filter to target intervals
if (!is.null(arguments$targets)) {

	target.intervals <- read.delim(arguments$targets, header = F);
	colnames(target.intervals)[1:3] <- c('Chromosome','Start','End');

	target.gr <- GRanges(target.intervals);

	overlaps <- as.data.frame(findOverlaps(refGene.gr, target.gr));

	refGene <- droplevels(refGene[unique(overlaps$queryHits),]);
	}

refGene$GeneID <- sapply(
        refGene$INFO,
        function(i) {
                parts <- unlist(strsplit(as.character(i), ';'));
                gene_name <- unlist(strsplit(parts[grepl('gene_id', parts)], ' '));
                gene_id  <- gene_name[length(gene_name)];
                return(gene_id);
                }
        );

refGene$Symbol <- sapply(
        refGene$INFO,
        function(i) {
                parts <- unlist(strsplit(as.character(i), ';'));
                gene_name <- unlist(strsplit(parts[grepl('gene_name', parts)], ' '));
                gene_symbol <- gene_name[length(gene_name)];
                return(gene_symbol);
                }
        );

refGene$Chromosome <- factor(refGene$Chromosome, levels = paste0('chr',c(1:22,'X','Y','M')));
refGene <- refGene[,-4];

gene.gr <- GRanges(refGene[,1:5]);

### MAIN ###########################################################################################
# find results files
ploidy.files <- list.files(pattern = 'alternative_solutions.txt$', recursive = TRUE);
seg.files <- list.files(pattern = 'segments.txt$', recursive = TRUE);

# read them in
ploidy.list <- list();

for (file in ploidy.files) {
	# extract sample ID
	smp <- unlist(strsplit(file, '\\/'));
	smp <- unlist(strsplit(smp[length(smp)], '_'))[1];
	# store data in list
	if (smp %in% names(ploidy.list)) { next; }
	ploidy.list[[smp]] <- read.delim(file);
	}

# format ploidy/cellularity results
ploidy.data <- do.call(rbind, ploidy.list);
ploidy.data$Sample <- sapply(rownames(ploidy.data), function(i) { unlist(strsplit(as.character(i),'\\.'))[1] } );
ploidy.data$Order <- sapply(rownames(ploidy.data), function(i) { unlist(strsplit(as.character(i),'\\.'))[2] } );
ploidy.data[is.na(ploidy.data$Order),]$Order <- 1;

# combine for writing
ploidy.formatted <- ploidy.data[which(ploidy.data$Order == 1),c('Sample','SLPP','cellularity','ploidy')];

# save combined/formatted data to file
write.table(
	ploidy.formatted,
	file = generate.filename(arguments$project, 'Sequenza_ploidy_purity','tsv'),
	row.names = FALSE,
	col.names = TRUE,
	sep = '\t'
	);

# and for segments
seg.list <- list();

for (file in seg.files) {
	# extract sample ID
	smp <- unlist(strsplit(file, '\\/'));
	smp <- unlist(strsplit(smp[length(smp)], '_'))[1];

	# store data in list
	if (smp %in% names(seg.list)) { next; }
	segs <- read.delim(file);
	seg.list[[smp]] <- segs[,c('chromosome','start.pos','end.pos','CNt')];
	}

# define a results table
gene.data <- refGene;
for (smp in names(seg.list)) {
	gene.data[,smp] <- 0;
	}

for (smp in names(seg.list)) {

	# convert to GRanges
	tmp <- seg.list[[smp]];
	colnames(tmp) <- c('chrom','start','end','CN');
	tmp$CN <- sign(tmp$CN-2);

	tmp <- tmp[which(tmp$CN != 0),];
	if (nrow(tmp) == 0) { next; }
	rownames(tmp) <- paste0('seg', 1:nrow(tmp));

	gr <- GRanges(tmp);

	# find overlap with genes (any amount of overlap)
	overlapGenes <- as.data.frame(findOverlaps(gr, gene.gr, minoverlap = 20));
	regionsWithHits <- as.data.frame(gr[unique(overlapGenes$queryHits)]);

	for (i in rownames(regionsWithHits)) {
		genes <- gene.gr[overlapGenes[which(overlapGenes$queryHits == sub('seg','',i)),]$subjectHits,]$GeneID;
		gene.data[which(gene.data$GeneID %in% genes),smp] <- tmp[i,]$CN;
		}
	}

write.table(
	gene.data,
	file = generate.filename(arguments$project, 'Sequenza_cna_gene_matrix', 'tsv'),
	row.names = FALSE,
	col.names = TRUE,
	sep = '\t'
	);

### SAVE SESSION INFO ##############################################################################
save.session.profile(generate.filename('CollectCNAs','SessionProfile','txt'));
