### collect_panelmsi_estimates.R ###################################################################
# Finds and combines output generated by panelMSI

### FUNCTIONS ######################################################################################
# function to generate a standardized filename
generate.filename <- function(project.stem, file.core, extension, include.date = TRUE) {

	# build up the filename
	file.name <- paste(project.stem, file.core, sep = '_');
	file.name <- paste(file.name, extension, sep = '.');

	if (include.date) {
		file.name <- paste(Sys.Date(), file.name, sep = '_');
		}

	return(file.name);
	}

# function to write session profile to file
save.session.profile <- function(file.name) {

	# open the file
	sink(file = file.name, split = FALSE);

	# write memory usage to file
	cat('### MEMORY USAGE ###############################################################');
	print(proc.time());

	# write sessionInfo to file
	cat("\n### SESSION INFO ###############################################################");
	print(sessionInfo());

	# close the file
	sink();

	}

### PREPARE SESSION ################################################################################
# import libraries
library(argparse);
library(plyr);

# import command line arguments
parser <- ArgumentParser();

parser$add_argument('-d', '--directory', type = 'character', help = 'path to data directory');
parser$add_argument('-p', '--project', type = 'character', help = 'project name');

arguments <- parser$parse_args();

# what's the date?
date <- Sys.Date();

setwd(arguments$directory);

### MAIN ###########################################################################################
# find results files
msi.files <- list.files(pattern = 'metrics.tsv$', recursive = TRUE);

# read them in
msi.list <- join_all(lapply(msi.files, function(i) {
	smp <- sub('_pertarget_msi_metrics.tsv','',basename(i));
	tmp <- read.delim(i);
	colnames(tmp)[which(colnames(tmp) == 'p.value')] <- smp;
	keep.fields <- setdiff(colnames(tmp), c('tumour_prop','normal_prop'));
	return(tmp[,keep.fields]);
	}));
	
# summarize results data
all.samples <- sapply(msi.files, function(i) { unlist(strsplit(basename(i),'_'))[1] } );

proportion.regions <- apply(
	msi.list[,all.samples],
	2,
	function(i) { length(i[which(i < 0.01)]) / length(na.omit(i)) }
	);

summarized.results <- data.frame(
	Sample = all.samples,
	N.regions = apply(msi.list[,all.samples],2,function(i) length(na.omit(i))),
	N.positive = apply(msi.list[,all.samples],2,function(i) length(i[which(i < 0.01)]) ),
	Proportion = apply(msi.list[,all.samples],2,function(i) length(i[which(i < 0.01)]) / 
		length(na.omit(i)) )
	);

# save combined/formatted data to file
write.table(
	summarized.results,
	file = generate.filename(arguments$project, 'panelMSI_estimates','tsv'),
	row.names = FALSE,
	col.names = TRUE,
	sep = '\t'
	);

write.table(
	msi.list,
	file = generate.filename(arguments$project, 'pertarget_msi_results','tsv'),
	row.names = FALSE,
	col.names = TRUE,
	sep = '\t'
	);

### SAVE SESSION INFO ##############################################################################
save.session.profile(generate.filename('CollectMSI','SessionProfile','txt'));
