#!/usr/bin/env perl
### generate_report.pl #############################################################################
use AutoLoader 'AUTOLOAD';
use strict;
use warnings;
use Carp;
use Getopt::Std;
use Getopt::Long;
use POSIX qw(strftime);
use File::Basename;
use File::Path qw(make_path);
use List::Util qw(any all first);
use List::MoreUtils qw(first_index);
use YAML qw(LoadFile);

####################################################################################################
# version       author		comment
# 1.0		sprokopec       tool to automatically generate reports

### USAGE ##########################################################################################
# generate_report.pl -d DATA_DIRECTORY -o OUTPUT_DIRECTORY
#
# where:

### MAIN ###########################################################################################
sub main {
	my %args = (
		patient_dir	=> undef,
		@_
		);

	# ensure no special characters in title
	my $title = basename($args{patient_dir});
	$title =~ s/_/\\_/g;

	# find all input files
	opendir(FILES, $args{patient_dir}) or die $!;
	my @input_files = readdir(FILES);
	closedir(FILES);

	my @tex_files = grep { /tex$/ } @input_files;
	@tex_files = sort @tex_files;

	# drop any previous instances of this report
	my @filtered_files = grep { $_ ne 'multiMMR_patient_report.tex' } @tex_files;

	# initiate report file
	open(my $report_file, '>', $args{patient_dir} . "/multiMMR_patient_report.tex");
	print $report_file <<EOI;

\\documentclass[12pt]{report}
\\usepackage{fancyhdr}
\\usepackage{graphicx}
\\usepackage{lastpage}
\\usepackage{caption}
\\usepackage{subcaption}
\\usepackage{url}
\\usepackage[margin=1in]{geometry}

\\usepackage{hyperref}
\\hypersetup{
        colorlinks=true,
        linktoc=all,
        linkcolor=black
        }

\\pagestyle{fancy}
\\lfoot{PughLab Pipeline-Suite}
\\rfoot{Run Date: \\today}
\\cfoot{Page \\thepage\\ of \\pageref{LastPage}}

\\title{\\Huge \\bf MultiMMR Report@{[defined $title ? ": $title" : ""]}}

\\date{
	\\centerline{This report was generated on \\today}}

\\renewcommand\\thesection{\\arabic{section}}

\\begin{document}

\\maketitle
\\thispagestyle{fancy}

\\pagebreak

\\tableofcontents

\\pagebreak

\\section{QC}

EOI

	# start with QC
	if (any { /qc_summary_sWGS.tex/ } @filtered_files) {
		print $report_file "\\input{qc_summary_sWGS.tex}\n";

		if (any { /ichor_estimates_sWGS.tex/ } @filtered_files) {
			print $report_file "\\input{ichor_estimates_sWGS.tex}\n";
			}

		print $report_file "\\pagebreak\n";
		}

	if (any { /qc_summary_EMSeq.tex/ } @filtered_files) {
		print $report_file "\\input{qc_summary_EMSeq.tex}\n";
		}

	if (any { /qc_summary_DNASeq.tex/ } @filtered_files) {
		print $report_file "\\input{qc_summary_DNASeq.tex}\n";
		}

	print $report_file "\\pagebreak\n";

	# add in combined data summary
	if (any { /complete_panel_summary.tex/ } @filtered_files) {
		print $report_file "\\input{complete_panel_summary.tex}\n";
		}

	# add in germline and somatic mutations
	if (any { /mutation_results.tex/ } @filtered_files) {
		print $report_file "\\input{mutation_results.tex}\n";
		}

	# add in methylation summary
	if (any { /methylation_estimates_EMSeq.tex/ } @filtered_files) {
		print $report_file "\\input{methylation_estimates_EMSeq.tex}\n";
		}

	# put the remaining tex files into output array
#	push @output_tex_files, @tex_files;

#	print $report_file "\\input{methods.tex}\n";

	print $report_file "\\section{Description}\n";
	print $report_file "This report was auto-generated by the PughLab Pipeline-Suite. The \\LaTeX \\ file used to generate this report is located at:\n";
	print $report_file "{\\scriptsize \\path{$args{patient_dir}/multiMMR_patient_report.tex}}\n\n";

	print $report_file "\\end{document}\n";
	close $report_file;
	}

### GETOPTS AND DEFAULT VALUES #####################################################################
# declare variables
my ($help, $output_directory);

# get command line arguments
GetOptions(
	'h|help'		=> \$help,
	'o|output_dir=s'	=> \$output_directory
	);

if ($help) {
	my $help_msg = join("\n",
		"Options:",
		"\t--help|-h\tPrint this help message",
		"\t--output_dir|-o\t<string> Path to output (report) directory"
		);

	print $help_msg . "\n";
	exit;
	}

# do some quick error checks to confirm valid arguments	
main(
	patient_dir	=> $output_directory
	);
