### plot_panel_summary.R ###########################################################################
# Plot data summary across targeted regions

### FUNCTIONS ######################################################################################
# function to generate a standardized filename
generate.filename <- function(project.stem, file.core, extension, include.date = TRUE) {

	# build up the filename
	file.name <- paste(project.stem, file.core, sep = '_');
	file.name <- paste(file.name, extension, sep = '.');

	if (include.date) {
		file.name <- paste(Sys.Date(), file.name, sep = '_');
		}

	return(file.name);
	}

# function to write session profile to file
save.session.profile <- function(file.name) {

	# open the file
	sink(file = file.name, split = FALSE);

	# write memory usage to file
	cat('### MEMORY USAGE ###############################################################');
	print(proc.time());

	# write sessionInfo to file
	cat("\n### SESSION INFO ###############################################################");
	print(sessionInfo());

	# close the file
	sink();

	}

# function to trim sample IDs
simplify.ids <- function(x) {
	match <- TRUE;
	if (length(x) == 1) {
		match <- FALSE;
		new.ids <- x;
		}
	index <- 1;
	while (match) {
		if (length(unique(sapply(x,function(i) { unlist(strsplit(i,''))[index] } ))) == 1) {
			index <- index + 1;
			} else {
			new.ids <- sapply(x,function(i) { substring(i,index,nchar(i)) } );
			match <- FALSE;
			}
		}
	return(new.ids);
	}

### PREPARE SESSION ################################################################################
# import command line arguments
library(argparse);

parser <- ArgumentParser();

parser$add_argument('-p', '--project', type = 'character', help = 'PROJECT name');
parser$add_argument('-o', '--output_dir', type = 'character', help = 'path to output directory');
parser$add_argument('-r', '--report_dir', type = 'character', help = 'path to report directory');
parser$add_argument('-s', '--sample_yaml', type = 'character', help = 'path to sample (BAM) yaml');
parser$add_argument('-c', '--cnas', type = 'character',
	help = 'path to gene by sample matrix of cna calls (generated by collect_panelCN_mops_output.R)');
parser$add_argument('-v', '--snp_dir', type = 'character', help = 'path to variant MAF files');
parser$add_argument('-m', '--methylation', type = 'character',
	help = 'path to per-site methylation matix (generated by collect_methyldackel_output.R)');
parser$add_argument('-g', '--genome', type = 'character', help = 'reference type', default = 'hg38');
parser$add_argument('-i', '--ichor', type = 'character', help = 'path to ichorCNA TF estimates');

arguments <- parser$parse_args();

###
#arguments$project <- 'MultiMMR';
#arguments$output_dir <- '/cluster/projects/pughlab/pughlab/projects/MultiMMR/DynaCare/TEST/SUMMARY'
#arguments$report_dir <- '/cluster/projects/pughlab/pughlab/projects/MultiMMR/DynaCare/TEST/Reports'
#arguments$sample_yaml <- '/cluster/projects/pughlab/pughlab/projects/MultiMMR/DynaCare/DNASeq/GATK/gatk_bam_config_2025-08-25_15-25-35.yaml'
#arguments$snp_dir <- '/cluster/projects/pughlab/pughlab/projects/MultiMMR/DynaCare/DNASeq/HaplotypeCaller/cohort/VCF2MAF';
#arguments$cnas <- '/cluster/projects/pughlab/pughlab/projects/MultiMMR/DynaCare/DNASeq/panelCNmops/2025-10-29_MultiMMR_panelCN.mops_output.tsv';
#arguments$methylation <- '/cluster/projects/pughlab/pughlab/projects/MultiMMR/DynaCare/EMSeq/MethylDackel/2025-10-10_MultiMMR_CpG_methylation_matrix.RData';
#arguments$ichor <- '/cluster/projects/pughlab/pughlab/projects/MultiMMR/DynaCare/sWGS/IchorCNA/2025-10-10_MultiMMR_ichorCNA_estimates.tsv';
###


# load libraries
library(BoutrosLab.plotting.general);
library(GenomicRanges);
library(plyr);
library(yaml);
library(xtable);

# what's the date?
date <- Sys.Date();

# get input files
output.dir <- arguments$output_dir;
reports.dir <- arguments$report_dir;

# create (if necessary) and move to output directory
if (!dir.exists(output.dir)) {
	dir.create(output.dir);
	}

if (!dir.exists(reports.dir)) {
	dir.create(reports.dir);
	}

genes.of.interest <- unlist(strsplit('MLH1|MLH3|MSH2|MSH3|MSH6|PMS2','\\|'));

### READ DATA ######################################################################################
# get data
if (!is.null(arguments$ichor)) {
	ichor.data <- read.delim(arguments$ichor);
	} else {
	ichor.data <- NULL;
	}

if (is.null(arguments$cnas)) {
	stop('ERROR: No CNA calls provided, please provide path to CNA matrix from panelCN.mops.');
	} else {
	cna.data <- read.delim(arguments$cnas, stringsAsFactors = FALSE);
	}

if (is.null(arguments$snp_dir)) {
	stop('ERROR: No SNP directory provided, please provide path to variant MAF file(s).');
	} else {
	snp.files <- list.files(path = arguments$snp_dir, pattern = 'maf$', full.names = TRUE);
	}

if (is.null(arguments$methylation)) {
	stop('ERROR: No methylation data provided, please provide path to methylation matrix.');
	} else {
	load(arguments$methylation);
	methylation.data <- full.methylation.data;
	rm(full.methylation.data);
	}

# parse sample information from yaml file
project.yaml <- read_yaml(arguments$sample_yaml);

sample.info <- as.data.frame(matrix(nrow = 0, ncol = 3));
colnames(sample.info) <- c('Patient','Sample','Type');

patients <- names(project.yaml);

for (patient in patients) {
	normals <- names(project.yaml[[patient]]$normal);
	tumours <- names(project.yaml[[patient]]$tumour);
	sample.info <- rbind(sample.info, 
		data.frame(Patient = rep(patient, length(normals)), Sample = normals, Type = rep('normal', length(normals))),
		data.frame(Patient = rep(patient, length(tumours)), Sample = tumours, Type = rep('tumour', length(tumours)))
		);
	}

sample.info$Patient <- as.character(sample.info$Patient);
sample.info$Sample <- as.character(sample.info$Sample);

sample.info <- sample.info[order(sample.info$Patient, sample.info$Sample),];
normal.smps <- sample.info[which(sample.info$Type == 'normal'),]$Sample;
tumour.smps <- sample.info[which(sample.info$Type == 'tumour'),]$Sample;


### FORMAT DATA ####################################################################################
# format CNA data
anno.fields <- c('Chr','Start','End','Gene','Exon');

if (any(is.na(cna.data$Gene))) {
	cna.data[is.na(cna.data$Gene),]$Gene <- 'region';
	}

gene.anno <- unique(cna.data[,anno.fields]);
target.regions <- makeGRangesFromDataFrame(gene.anno,
	keep.extra.columns = TRUE,
	seqnames.field = 'Chr',
	start.field = 'Start',
	end.field = 'End');

# calculate log2ratios
cna.data$Ratio <- log2(cna.data$RC.norm / cna.data$medRC.norm);

# set minimum ratio to -2 (to deal with -Inf)
cna.data$CN.Abs <- as.numeric(gsub('CN','',cna.data$CN))-2;
if (any(cna.data$CN == 'CN0')) {
	cna.data[which(cna.data$CN == 'CN0'),]$CN.Abs <- -2;
	}

# convert to region x sample matrix
cna.matrix <- reshape(
	cna.data[,c('Chr','Start','End','Gene','Exon','Sample','CN.Abs')],
	direction = 'wide',
	idvar = c('Chr','Start','End','Gene','Exon'),
	timevar = 'Sample'
	);
colnames(cna.matrix) <- gsub('CN.Abs.','',colnames(cna.matrix));

cna.matrix$Chr <- factor(cna.matrix$Chr, levels = paste0('chr',1:22));
cna.matrix <- cna.matrix[order(cna.matrix$Chr, cna.matrix$Start),];

# convert to region x sample matrix
ratio.matrix <- reshape(
	cna.data[,c('Chr','Start','End','Gene','Exon','Sample','Ratio')],
	direction = 'wide',
	idvar = c('Chr','Start','End','Gene','Exon'),
	timevar = 'Sample'
	);
colnames(ratio.matrix) <- gsub('Ratio.','',colnames(ratio.matrix));

ratio.matrix$Chr <- factor(ratio.matrix$Chr, levels = paste0('chr',1:22));
ratio.matrix <- ratio.matrix[order(ratio.matrix$Chr, ratio.matrix$Start),];

# get sample ids
cna.samples <- setdiff(colnames(ratio.matrix), anno.fields);

# run segmentation
CNAobj <- DNAcopy::CNA(ratio.matrix[,cna.samples], chrom = ratio.matrix$Chr, maploc = ratio.matrix$Start,
	data.type = 'logratio', sampleid = cna.samples, presorted = TRUE);

seg.data <- DNAcopy::segment(CNAobj)$output;
if (any(!cna.samples %in% seg.data$ID)) {
	seg.data$ID <- gsub('\\.','-',seg.data$ID);
	}


# format SNP data
snp.data <- do.call(rbind, lapply(snp.files, read.delim, comment.char = '#'));
snp.data$t_vaf <- snp.data$t_alt_count / snp.data$t_depth;
snp.data$n_vaf <- snp.data$n_alt_count / snp.data$n_depth;
snp.samples <- unique(snp.data$Tumor_Sample_Barcode);


# format methylation data
m.data <- list();
for (patient in unique(sample.info$Patient)) {
	tumours <- sample.info[which(sample.info$Patient == patient & 
		sample.info$Type == 'tumour'),]$Sample;
	tumours <- intersect(tumours, colnames(methylation.data));
	if (length(tumours) == 0) { next; }

	normals <- sample.info[which(sample.info$Patient == patient &
		sample.info$Type == 'normal'),]$Sample;
	normals <- intersect(normals, colnames(methylation.data));
	if (length(normals) == 0) {
		normals <- intersect(sample.info[which(sample.info$Type == 'normal'),]$Sample,
			colnames(methylation.data));
		}
	if (length(normals) == 0) { next; }

	anno.data <- methylation.data[,1:3];
	n.data <- if (length(normals) > 1) {
		apply(methylation.data[,normals],1,mean,na.rm = TRUE);
		} else { methylation.data[,normals]; }
	t.data <- methylation.data[,tumours] - n.data;

	m.data[[patient]] <- na.omit(cbind(anno.data, t.data));
	colnames(m.data[[patient]]) <- c(colnames(anno.data),tumours);
	}

methyl.data <- join_all(m.data);


# set up colour schemes
colour.scheme <- c('magenta1','black','darkolivegreen1');
colour.function.low <- colorRamp(colour.scheme[1:2], space = 'Lab');
colour.function.high <- colorRamp(colour.scheme[2:3], space = 'Lab');

methyl.colours <- c(
	rgb(colour.function.low(seq(0,0.9,0.1)^(1/0.3)), maxColorValue = 255),
	colour.scheme[2],
	rgb(colour.function.high(seq(0.1,1,0.1)^(0.3)), maxColorValue = 255)
	)
methyl.legend.labels <- rep(NA, length(methyl.colours));
methyl.legend.labels[c(1,11,21)] <- c('-1','0','+1');

colour.scheme <- colorRampPalette(c('blue','grey90','red'));
cna.colours <- colour.scheme(length(seq(-1,1,0.1)));
cna.legend.labels <- rep(NA, length(cna.colours));
cna.legend.labels[c(1,11,21)] <- c('-1','0','+1');

abs.colours <- cna.colours[c(1,6,11,16,21)];
names(abs.colours) <- c('-2','-1','0','1','2');

# move to output directory
setwd(output.dir);

# set up data template
template <- data.frame(slidingWindows(target.regions,1));
template$Exon <- factor(
	template$group,
	levels = c(1:length(target.regions)),
	labels = target.regions$Exon
	);

colnames(template)[3:4] <- c('chromosome','position');
template <- template[,c('chromosome','position','Exon')];

template$Order <- 1:nrow(template);

template <- merge(template, gene.anno[,c('Exon','Gene')]);
template <- template[order(template$Order),];

# prepare data for each sample
sample.data <- list();

for (smp in tumour.smps) {

	# get gene data for this sample
	cn.to.plot <- cna.matrix[,c(anno.fields, smp)];
	lrr.to.plot <- ratio.matrix[,c(anno.fields, smp)];
	seg.to.plot <- seg.data[which(seg.data$ID == smp),];
	snp.to.plot <- snp.data[which(snp.data$Tumor_Sample_Barcode == smp),];
	methyl.to.plot <- methyl.data[,c('seqnames','start','end',smp)];

	# check for data completeness
	if (!smp %in% colnames(cna.matrix)) {
		smp.data <- template;
		smp.data[,c('CN','c.colour')] <- NA;
		} else {

		# format log-ratio values
		smp.data <- merge(
			template, 
			cn.to.plot[,c('Chr','Exon',smp)], 
			by.x = c('chromosome','Exon'),
			by.y = c('Chr','Exon'),
			all.x = TRUE
			);
		colnames(smp.data)[which(colnames(smp.data) == smp)] <- 'CN';
		smp.data$c.colour <- abs.colours[match(as.character(smp.data$CN), names(abs.colours))];
		}

	# check for data completeness
	if (!smp %in% colnames(ratio.matrix)) {
		smp.data <- template;
		smp.data[,c('LRR','r.colour')] <- NA;
		} else {

		# format log-ratio values
		smp.data <- merge(
			smp.data, 
			lrr.to.plot[,c('Chr','Exon',smp)], 
			by.x = c('chromosome','Exon'),
			by.y = c('Chr','Exon'),
			all.x = TRUE
			);
		colnames(smp.data)[which(colnames(smp.data) == smp)] <- 'LRR';
		smp.data$r.colour <- 'black';
		}

	# check for data completeness
	if (!smp %in% snp.data$Tumor_Sample_Barcode) {
		smp.data[,c('BAF','b.colour')] <- NA;
		} else {
		# format B-allele frequencies
		snp.idx <- which(is.na(snp.to.plot$n_vaf) | (
			snp.to.plot$n_vaf >= 0.35 & snp.to.plot$n_vaf <= 0.65));
		smp.data <- merge(
			smp.data,
			snp.to.plot[snp.idx,c('Chromosome','Start_Position','t_vaf')], 
			by.x = c('chromosome','position'),
			by.y = c('Chromosome','Start_Position'),
			all.x = TRUE
			);
		colnames(smp.data)[which(colnames(smp.data) == 't_vaf')] <- 'BAF';
		smp.data$b.colour <- 'black';
		if (any(na.omit(smp.data$BAF) < 0.1 | na.omit(smp.data$BAF) > 0.9)) {
			smp.data[which(smp.data$BAF < 0.1 | smp.data$BAF > 0.9),]$b.colour <- 'orange'; 
			}
		}

	# check for data completeness
	if (!smp %in% colnames(methyl.data)) {
		smp.data[,c('Methylation','m.colour')] <- NA;
		} else {
		# format methylation levels
		smp.data <- merge(
			smp.data,
			methyl.to.plot[,c('seqnames','start',smp)], 
			by.x = c('chromosome','position'),
			by.y = c('seqnames','start'),
			all.x = TRUE
			);
		colnames(smp.data)[which(colnames(smp.data) == smp)] <- 'Methylation';
		smp.data$m.colour <- methyl.colours[match(as.character(round(smp.data$Methylation,1)), seq(-1,1,0.1))];
		}

	# check for data completeness
	if (!smp %in% seg.data$ID) {
		smp.data[,c('CN.Seg','s.colour')] <- NA;
		} else {
		# format CN segment calls
		tmp <- makeGRangesFromDataFrame(smp.data,
			seqnames.field = 'chromosome',
			start.field = 'position',
			end.field = 'position',
			keep.extra.columns = TRUE
			);

		segs <- makeGRangesFromDataFrame(seg.to.plot,
			seqnames.field = 'chrom',
			start.field = 'loc.start',
			end.field = 'loc.end',
			keep.extra.columns = TRUE
			);

		tmp2 <- mergeByOverlaps(tmp, segs);
		df <- data.frame(tmp2$tmp, tmp2$seg.mean);

		smp.data <- merge(
			smp.data,
			df[,c('seqnames','start','tmp2.seg.mean')],
			by.x = c('chromosome','position'),
			by.y = c('seqnames','start'),
			all.x = TRUE
			);
		colnames(smp.data)[which(colnames(smp.data) == 'tmp2.seg.mean')] <- 'CN.Seg';
		smp.data$s.colour <- cna.colours[match(as.character(round(smp.data$CN.Seg,1)), seq(-1,1,0.1))];
		if (any(na.omit(smp.data$CN.Seg) < -1)) {
			smp.data[which(smp.data$CN.Seg < -1),]$s.colour <- cna.colours[1];
			}
		if (any(na.omit(smp.data$CN.Seg) > 1)) {
			smp.data[which(smp.data$CN.Seg > 1),]$s.colour <- cna.colours[length(cna.colours)];
			}
		}

	sample.data[[smp]] <- smp.data;
	}

rm(smp.data, tmp, segs, tmp2, df, cn.to.plot, seg.to.plot, snp.to.plot, methyl.to.plot);

save(
	sample.data,
	file = generate.filename(arguments$project, 'summarized_panel_data', 'RData')
	);

# run unlink, in case it exists from a previous run
unlink('summarized_panel_data.RData');

file.symlink(
	generate.filename(arguments$project, 'summarized_panel_data', 'RData'),
	'summarized_panel_data.RData'
	);


### MAKE PLOTS #####################################################################################
new.axis.function <- function(side, line.col = "black", ...) {
	if (side %in% c("left")) {
		axis.default(side = side, line.col = "black", ...);
		lims <- current.panel.limits();
		panel.abline(h = lims$ylim[1], v = lims$xlim[1]);
		}
	}

# find chromosome breaks
get.midpoints <- function(x) {
	y <- get.line.breaks(x)+0.5;
	(c(1, y) - 1) + ( c(y, length(x)) - c(1, y) ) / 2
	}
chr.breaks <- get.line.breaks(template$chromosome);
chr.midpoints <- get.midpoints(template$chromosome);

# find genes of interest
gene.pos <- aggregate(Order ~ Gene, template[which(template$Gene %in% genes.of.interest),], median);

# create some common covariates
gene.data <- as.data.frame(matrix(nrow = nrow(template), ncol = 2, data = 0));
colnames(gene.data) <- c('Order','roi');
gene.data$Order <- template$Order;
gene.data[which(template$Gene %in% genes.of.interest),]$roi <- 1;

# create some legends
plot.legends <- list(
	legend = list(
		colours = 'orange',
		labels = 'LOH'
		),
	legend = list(
		title = 'CN Segment',
		colours = c('blue','grey90','red'),
		labels = c('-2','0','2'),
		continuous = TRUE,
		tck = 0.5,
		tck.number = 2,
		width = 5,
		height = 1,
		angle = 1
		),
	legend = list(
		title = 'Methylation',
		colours = c('magenta1','black','darkolivegreen1'),
		labels = c('-1','0','1'),
		continuous = TRUE,
		tck = 0.5,
		tck.number = 2,
		width = 5,
		height = 1,
		angle = 1
		)
	);

my.legend.grob <- legend.grob(
	legends = plot.legends,
	title.just = 'left',
	label.cex = 0.7,
	title.cex = 0.7,
	size = 1.5,
	between.col = 4,
	layout = c(3,1) 
	);

# make gene plot with legend
gene.covariates <- create.scatterplot(
	roi ~ Order,
	gene.data,
	type = 'h',
	cex = 0,
	xlimits = c(0,nrow(gene.data)),
	ylimits = c(0,1),
	xlab.label = NULL,
	ylab.label = NULL,
	xat = gene.pos$Order,
	xaxis.lab = gene.pos$Gene,
	xaxis.rot = 45,
	xaxis.cex = 0.8,
	yaxis.lab = NULL,
	xaxis.tck = 0,
	yaxis.tck = 0,
	legend = list(inside = list(fun = my.legend.grob, x = 0, y = -7)),
	style = 'Nature'
	);

caption <- "Complete data summary across the MultiMMR panel: BAF = b-allele frequency for SNVs (SNPs and/or small INDELs heterozygous in germline) in the tumour sample; LRR = log2(reads ratio) for CN calls with segmentation by CBS; CN Call = absolute CN call from panelCN.mops; Methylation = relative methylation levels (vs matched normal or panel of normals where available).";


### PER-SAMPLE SUMMARIES ###########################################################################
setwd(reports.dir);

# initiate report object
tex.file <- 'complete_panel_summary.tex';

for (patient in unique(sample.info$Patient)) {

	if (!dir.exists(patient)) {
		dir.create(patient);
		}

	setwd(patient);

	patient.data <- sample.info[which(sample.info$Patient == patient),];

	# is a matched normal present?
	matched.normal <- if (any(patient.data$Type == 'normal')) {
		patient.data[which(patient.data$Type == 'normal'),]$Sample[1];
		} else { 'panelOfNormals'; }

	patient.data <- patient.data[which(patient.data$Type == 'tumour'),];

	# add data to tex file
	write("\\section{Panel Summary}\n", file = tex.file);

	for (smp in patient.data$Sample) {

		# pull ichorCNA estimates
		tf.key <- NULL;
		if (!is.null(ichor.data)) {
			tf <- round(ichor.data[which(ichor.data$ID == smp),]$Tumour.Fraction,2);
			tf.key <- list(
				text = list(lab = c(
					paste0('Tumour sample: ', smp),
					paste0('Normal used for reference: ', matched.normal),
					paste0('Tumour fraction (ichorCNA) = ', tf)))
				);
			}

		# get gene data for this sample
		smp.data <- sample.data[[smp]];

		# plot SNP frequencies
		baf.plot <- create.scatterplot(
			BAF ~ Order,
			smp.data,
			col = smp.data$b.colour,
			alpha = 0.8,
			cex = 0.8,
			xlimits = c(0,nrow(template)),
			ylimits = c(0,1),
			xat = chr.midpoints,
			xaxis.lab = c(1:20,'21\n','22'),
			yat = seq(0,1,0.5),
			xaxis.tck = c(0.5,0),
			yaxis.tck = c(0.5,0),
			xaxis.cex = 1,
			yaxis.cex = 1,
			xlab.label = NULL,
			ylab.label = 'BAF',
			ylab.cex = 1.5,
			add.rectangle = TRUE,
			xleft.rectangle = c(0,chr.breaks),
			xright.rectangle = c(chr.breaks, nrow(template)),
			ytop.rectangle = 5,
			ybottom.rectangle = -5,
			col.rectangle = c('grey90','white'),
			alpha.rectangle = 0.5,
			style = 'Nature'
			);

		baf.axis.function <- function(side, line.col = "black", ...) {
			if (side %in% c("left","top")) {
				axis.default(side = side, line.col = "black", ...);
				lims <- current.panel.limits();
				panel.abline(h = lims$ylim[2], v = lims$xlim[1]);
				}
			}

		baf.plot$axis <- baf.axis.function;
		baf.plot$x.scales$alternating <- 2;

		# plot LRR values
		lrr.plot <- create.scatterplot(
			LRR ~ Order,
			smp.data,
			col = smp.data$r.colour,
			alpha = 0.8,
			cex = 0.8,
			xlimits = c(0,nrow(template)),
			ylimits = c(-2,2),
			xaxis.lab = NULL,
			yat = seq(-2,2,1),
			xaxis.tck = 0,
			yaxis.tck = c(0.5,0),
			yaxis.cex = 1,
			xlab.label = NULL,
			ylab.label = 'LRR',
			ylab.cex = 1.5,
			add.rectangle = TRUE,
			xleft.rectangle = c(0,chr.breaks),
			xright.rectangle = c(chr.breaks, nrow(template)),
			ytop.rectangle = 5,
			ybottom.rectangle = -5,
			col.rectangle = c('grey90','white'),
			alpha.rectangle = 0.5,
			add.grid = TRUE,
			ygrid.at = 0,
			xgrid.at = -1,
			add.points = TRUE,
			points.col = smp.data$s.colour,
			points.cex = 0.3,
			points.alpha = 0.8,
			points.x = smp.data$Order,
			points.y = smp.data$CN.Seg,
			style = 'Nature'
			);

		# plot CN segment ratios
		cn.plot <- create.scatterplot(
			CN ~ Order,
			smp.data,
			col = smp.data$c.colour,
			alpha = 0.8,
			cex = 0.6,
			xlimits = c(0,nrow(template)),
			ylimits = c(-2,2),
			xaxis.lab = NULL,
			yat = seq(-2,2,1),
			xaxis.tck = 0,
			yaxis.tck = c(0.5,0),
			yaxis.cex = 1,
			xlab.label = NULL,
			ylab.label = 'CN Call',
			ylab.cex = 1.5,
			add.rectangle = TRUE,
			xleft.rectangle = c(0,chr.breaks),
			xright.rectangle = c(chr.breaks, nrow(template)),
			ytop.rectangle = 5,
			ybottom.rectangle = -5,
			col.rectangle = c('grey90','white'),
			alpha.rectangle = 0.5,
			add.grid = TRUE,
			ygrid.at = 0,
			xgrid.at = -1,
			style = 'Nature'
			);

		# plot methylation levels
		methyl.plot <- create.scatterplot(
			Methylation ~ Order,
			smp.data,
			col = smp.data$m.colour,
			alpha = 0.8,
			cex = 0.8,
			xlimits = c(0,nrow(template)),
			ylimits = c(-1,1),
			yat = seq(-1,1,1),
			xaxis.tck = 0,
			yaxis.tck = c(0.5,0),
			yaxis.cex = 1,
			xaxis.fontface = 'italic',
			xlab.label = NULL,
			ylab.label = 'Methylation',
			ylab.cex = 1.5,
			add.rectangle = TRUE,
			xleft.rectangle = c(0,chr.breaks),
			xright.rectangle = c(chr.breaks, nrow(template)),
			ytop.rectangle = 5,
			ybottom.rectangle = -5,
			col.rectangle = c('grey90','white'),
			alpha.rectangle = 0.5,
			add.grid = TRUE,
			ygrid.at = 0,
			xgrid.at = -1,
			style = 'Nature'
			);

		lrr.plot$axis <- new.axis.function;
		cn.plot$axis <- new.axis.function;
		methyl.plot$axis <- new.axis.function;

		# combine them
		create.multipanelplot(
			plot.objects = list(baf.plot, lrr.plot, cn.plot, methyl.plot, gene.covariates),
			layout.width = 1,
			layout.height = 5,
			plot.objects.heights = c(1.1,1,1,1,0.5),
			plot.objects.widths = 1,
			left.legend.padding = 0,
			right.legend.padding = 0,
			top.legend.padding = 0,
			bottom.legend.padding = 0,
			bottom.padding = 3,
			y.spacing = c(-2.5,-1.5,-1.5,-1.5,-1.5),
			x.spacing = 0,
			ylab.axis.padding = 1,
			legend = list(
				inside = list(fun = draw.key, args = list(key = tf.key), x = 0.85, y = 0.06)
				),
			height = 8,
			width = 16,
			resolution = 200,
			filename = generate.filename(smp, '_panel_summary', 'png')
			);

		# add data to tex file
		write("\\begin{figure}[h!]", file = tex.file, append = TRUE);
		write("\\begin{center}", file = tex.file, append = TRUE);
		write(paste0(
			"\\includegraphics[width=1\\textwidth]{",
			generate.filename(smp, '_panel_summary','png'), '}'
			), file = tex.file, append = TRUE);
		write("\\end{center}", file = tex.file, append = TRUE);
		write(paste0(
			"\\caption{", caption, "}"
			), file = tex.file, append = TRUE);
		write("\\end{figure}\n", file = tex.file, append = TRUE);
		write("\\pagebreak\n", file = tex.file, append = TRUE);
		}

	setwd(reports.dir);
	}

### SAVE SESSION INFO ##############################################################################
setwd(output.dir);
save.session.profile(generate.filename(arguments$project, 'PlotPanelSummary_SessionProfile','txt'));
